<?php
$this->headLink()->prependStylesheet($this->basePath() . '/css/jquery-ui-1.7.2.custom.css')
        ->prependStylesheet($this->basePath() . '/assets/lib/fancybox/jquery.fancybox.css')
        ->prependStylesheet($this->basePath() . '/assets/lib/chosen/chosen.css');

$this->headScript()
        ->prependFile($this->basePath() . '/assets/lib/touch-punch/jquery.ui.touch-punch.min.js')
        ->prependFile($this->basePath() . '/assets/lib/datatables/DT_bootstrap.js')
        ->prependFile($this->basePath() . '/js/jquery-ui.js')
        ->prependFile($this->basePath() . '/assets/lib/fancybox/jquery.fancybox.js');

$user_contacts = $this->contacts;
?>
<?= $this->partial('layout/top_links'); ?>
<div class="layout_nav">
        <ul>
            <li><a class="before" href="<?php echo $this->basePath('/'); ?>">Home &rsaquo; </a></li>    
             <li><a class="before" href="<?php echo $this->url('scn-social-connections'); ?>">My Connections &rsaquo; </a></li>    
            <li>Add Connections</li> 
        </ul>
 </div>
<div class='clear'></div>
<?php if ($this->message != '') { ?>
    <div class="flash_message">
        <?php echo $this->message[0]; ?>
    </div>
<?php } ?>
<?php if ($this->errorMessage != '') { ?>
    <div class="error_message">
        <?php echo $this->errorMessage[0]; ?>
    </div>
<?php } ?>
<div class="myaccount">
    <div style="display: inline-block;border-bottom: 1px solid #dfdfdf;width: 100%;">
        <h3 style='border:none;float: left;'>My connections</h3>         
    </div>
    <div style="padding:10px;width:60%">

        <div class="maincontent">          
            <?php
            $title = 'Add new connection';
            $this->headTitle($title);
            ?>
            <h5><?php echo $this->escapeHtml($title); ?></h5>
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('scn-social-connections', array('action' => 'add')));
            $form->setAttribute('class', 'zend_form');
            $form->prepare();

            echo $this->form()->openTag($form);
            //echo $this->formCollection($form);
            echo $this->formLabel($form->get('name'));
            echo $this->formInput($form->get('name'));
            echo $this->formElementErrors($form->get('name'), array('class' => "valuerequired", 'message' => "name required"));
            echo $this->formLabel($form->get('email'));
            echo $this->formInput($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            echo $this->formLabel($form->get('relation'));
            echo $this->formInput($form->get('relation'));
            echo $this->formElementErrors($form->get('relation'));
            echo $this->formHidden($form->get('user_id'));
            echo $this->formInput($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            if (count($user_contacts) > 0) {
                ?>
                <a class="fancybox btn  btn-default float-left" style="margin: 10px;" href="#contacts">Add contacts</a>
            <?php
            }
            echo $this->form()->closeTag();
            ?>

        </div>
        <div id="contacts" style="display: none;">
            <div class="import_contacts">
                <input type="text" class="input-small form-control" id="socialuser" placeholder="Live Search ...">
                <ul id="list">

                    <?php
                    try {
                        if (count($user_contacts) <= 0) {
                            echo "No contact found!";
                        }

                        // grab the user contacts list                
                        if (count($user_contacts) > 0) {
                            foreach ($user_contacts as $item) {
                                if (filter_var($item->identifier, FILTER_VALIDATE_EMAIL)) {
                                    $item->identifier = $item->identifier;
                                } else {

                                    $item->identifier = $item->identifier . '@facebook.com';
                                }
                                if ($item->displayName != '') {
                                    ?>
                                    <li>
                                        <input type="checkbox" class="case" name="ids[]" value="<?php echo $item->identifier ?>" data-name="<?php echo $item->displayName; ?>">
                                        <?php if ($item->photoURL) { ?>
                                            <?php /* <input class="floatleft conatctcheck" type="checkbox" name="users[]" data-name="<?php echo $item->displayName; ?>" data-id="<?php echo $item->identifier; ?>" data-url="<?php echo $item->photoURL; ?>" />
                                             */ ?> 
                                            <a class="socialuser" id="<?php echo $item->identifier; ?>" data-email="<?php echo $item->email; ?>" data-id="<?php echo $item->identifier; ?>" data-url="<?php echo $item->photoURL; ?>" 
                                               data-name="<?php echo $item->displayName; ?>" data-dob="<?php echo $item->birthday; ?>"  data-loc="<?php echo $item->location; ?>"  data-home="<?php echo $item->home; ?>" data-company="<?php echo $item->company; ?>" data-job="<?php echo $item->jobTitle; ?>" 
                                               href="#/<?php echo $item->displayName; ?>/" style="background:url('<?php echo $item->photoURL; ?>') no-repeat left center / 48px "><?php echo $item->displayName; ?></a>

                                        <?php } else { ?> 
                                            <?php /* <input class="floatleft" type="checkbox" name="users[]" data-name="<?php echo $item->displayName; ?>" data-id="<?php echo $item->identifier; ?>" data-url="<?php echo $this->basePath('/img/avatar.jpg'); ?>" />
                                             */ ?>
                                            <a class="socialuser" id="<?php echo $item->identifier; ?>" data-email="<?php echo $item->email; ?>" data-id="<?php echo $item->identifier; ?>" data-url="<?php echo $this->basePath('/img/avatar.jpg'); ?>" 
                                               data-name="<?php echo $item->displayName; ?>" data-dob="<?php echo $item->birthday; ?>"  data-loc="<?php echo $item->location; ?>"  data-home="<?php echo $item->home; ?>" data-company="<?php echo $item->company; ?>" data-job="<?php echo $item->jobTitle; ?>" 
                                               href="#/<?php echo $item->displayName; ?>/" style="background:url('<?php echo $this->basePath('/img/avatar.jpg'); ?>') no-repeat left center / 48px "><?php echo $item->displayName; ?></a>

                <?php } ?>  

                                    </li> 
                                    <?php
                                }
                            }
                        }
                    } catch (Exception $e) {
                        // if code 8 => Provider does not support this feature
                        if ($e->getCode() == 8) {
                            echo "Provider does not support this feature. Currently only <b>Facebook, MySpace, Twitter and LinkedIn</b> do support this!
    					<br />Please refer to the user guide to know more about each adapters capabilities. <a href='http://hybridauth.sourceforge.net/userguide.html'>http://hybridauth.sourceforge.net/userguide.html</a>";
                        } else {
                            echo "Well, got an error: " . $e->getMessage();
                        }
                    }
                    ?>
                </ul>
                <button class="btn btn-default btn-sm" id="import">Import</button>
            </div>
            
        </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart() ?>



<?php $this->inlineScript()->captureEnd() ?>