
<div class="header-bottom">
	<div class="col-md-4 col-sm-4">
		<a class="logo-top" href="#">Cremation Planning <i
			class="fa fa-chevron-right"></i></a> <a class="main-slide" href="#">Announce</a>
	</div>

	<div class="col-md-4 col-sm-5 col-xs-7 bread-crum-mob " style="margin-left:-100px;">
		<div class="button-radio">
			<input type="radio" class="css-checkbox" id="radiofirst"
				name="radiog_lite" checked="checked"> <label
				class="css-label1 radGroup1" for="radiofirst">Create New</label> <input
				type="radio" class="css-checkbox" id="radiosecond"
				name="radiog_lite"> <label class="css-label1 radGroup1"
				for="radiosecond">Created Profiles</label>
		</div>
	</div>

	<div class="col-md-4 col-sm-3 col-xs-5 pull-right bread-crum-mob">
		<div class="floatr border-full pull-right">
			<a class="alls first" href="page/faq">FAQ</a><a class="alls second"
				href="page/demo">Demo</a><a class="alls third" href="page/share">Share</a>
		</div>
	</div>
	<div class="flash_message"> <?php echo $message; ?></div>
	<div class="clearfix"></div>
</div>
