<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Add new Category')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('tasks' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/tasks', array('action' => 'add')));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>