<?= $this->partial('layout/top_links'); ?>
<div class="layout_nav">
        <ul>
            <li><a class="before" href="<?php echo $this->basePath('/'); ?>">Home &rsaquo; </a></li>           
            <li>Change Password</li> 
        </ul>
 </div>
<div class='clear'></div>
<div class="myaccount">
    <h3>Change Password</h3>
    <div style="padding:10px;width:60%">
        <div class="maincontent">
        <?php if ($status === true) : ?>
            <div class="success">Password changed successfully.</div>
             <?php elseif ($status == 'uniq') : ?>
            <div class="error">Current password and new password should not be same</div>    
             <?php elseif ($status == 'orginal') : ?>
            <div class="error">Current password is wrong</div> 
        <?php elseif ($status === false) : ?>
            <div class="error">Unable to update your password. Please try again.</div>
        <?php endif; ?>
        <?php
        $form = $this->changePasswordForm;

        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/changepassword'));
        $form->setAttribute('method', 'post');

        $emailElement = $form->get('identity');
        $emailElement->setValue($this->zfcUserIdentity()->getEmail());

        echo $this->form()->openTag($form);
        ?>
        <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')); ?>
            <dd><?php echo $this->formInput($form->get('identity')); ?></dd>

            <dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
            <dd><?php
        echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
        ?></dd>

            <dt><?php echo $this->formLabel($form->get('newCredential')); ?></dt>
            <dd><?php
                echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
        ?></dd>

            <dt><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></dt>
            <dd><?php
                echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
        ?></dd>
            <dt><?php echo $this->formLabel($form->get('captcha')); ?></dt>
            <dd><?php echo $this->formElement($form->get('captcha')); ?></dd>
            <dt>&nbsp;</dt>
            <dd><?php
//echo $this->formInput($form->get('csrf'));
            
                echo $this->formInput($form->get('submit'));
        ?></dd>

        </dl>

<?php echo $this->form()->closeTag(); ?>
    </div>
</div>
    
</div>