<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Delete Category')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('cms' => 'active')); ?></div> 
<div class="myaccount">
    <h3>Change Password</h3>
    <div class="mainaccount">
        <div class="maincontent">
            <div class="alertbox">
            <p>Are you sure that you want to delete
                '<?php echo $this->escapeHtml($this->cms->title); ?>'?
            </p>
            <?php
            $url = $this->url('admin/cms', array(
                'action' => 'delete',
                'id' => $this->cms->id,
            ));
            ?>
            <form action="<?php echo $url; ?>" method="post">
                <div>
                    <input type="hidden" name="id" value="<?php echo (int) $this->cms->id; ?>" />
                    <input type="submit" name="del" value="Yes" />
                    <input type="submit" name="del" value="No" />
                </div>
            </form>
        </div>
    </div>
</div>
</div>
