
<div class="header-bottom">
<div class="col-md-4">
<a class="logo-top" href="#">Cremation Planning <i class="fa fa-chevron-right"></i></a>
<a class="main-slide" href="#">Announce</a>
</div>

<div class="col-md-4">
<div class="button-radio">
<label class="radio-inline set-radio1">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1"> Create New
</label>
<label class="radio-inline set-radio2">
  <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> My Accout
</label>
</div>
</div>

<div class="col-md-4">
<div class="floatr border-full">
<a class="alls first" href="#">FAQ</a><a class="alls second" href="#">Demo</a><a class="alls third" href="#">Share</a>
</div>
</div>

<div class="clearfix"></div>
</div>

<!-- section-band,col-md-4 border-right text-center -->
<div class="section-band">
<div class="col-md-4 border-right text-center">
<!--starting of slider -->





    <!-- it works the same with all jquery version from 1.x to 2.x -->
    <script type="text/javascript" src="../js/jquery-1.9.1.min.js"></script>
    <!-- use jssor.slider.mini.js (40KB) instead for release -->
    <!-- jssor.slider.mini.js = (jssor.js + jssor.slider.js) -->
    <script type="text/javascript" src="../js/jssor.js"></script>

	
 <script>
        jQuery(document).ready(function ($) {
            var options = {
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlayInterval: 4000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $SlideDuration: 500,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
                $UISearchMode: 0,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).

                $ThumbnailNavigatorOptions: {
                    $Class: $JssorThumbnailNavigator$,              //[Required] Class to create thumbnail navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always

                    $Loop: 2,                                       //[Optional] Enable loop(circular) of carousel or not, 0: stop, 1: loop, 2 rewind, default value is 1
                    $SpacingX: 3,                                   //[Optional] Horizontal space between each thumbnail in pixel, default value is 0
                    $SpacingY: 3,                                   //[Optional] Vertical space between each thumbnail in pixel, default value is 0
                    $DisplayPieces: 6,                              //[Optional] Number of pieces to display, default value is 1
                    $ParkingPosition: 204,                          //[Optional] The offset position to park thumbnail,

                    $ArrowNavigatorOptions: {
                        $Class: $JssorArrowNavigator$,              //[Requried] Class to create arrow navigator instance
                        $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                        $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                        $Steps: 6                                       //[Optional] Steps to go for each navigation request, default value is 1
                    }
                }
            };

            var jssor_slider1 = new $JssorSlider$("slider1_container", options);

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                if (parentWidth)
                    jssor_slider1.$ScaleWidth(Math.min(parentWidth, 444));
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>
    <!-- Jssor Slider Begin -->
    <!-- You can move inline styles to css file or css block. -->
    <div id="slider1_container" style="position: relative; width: 444px;
        height: 441px; overflow: hidden;">

        <!-- Loading Screen -->
        <div u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
                background-color: #000; top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
            <div style="position: absolute; display: block; background: url(images/loading.gif) no-repeat center center;
                top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
        </div>

        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 444px; height: 441px;
            overflow: hidden;">
            <div>
                <img u="image" src="images/travel/01.jpg" />
                <img u="thumb" src="images/travel/thumb-01.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/02.jpg" />
                <img u="thumb" src="images/travel/thumb-02.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/03.jpg" />
                <img u="thumb" src="images/travel/thumb-03.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/04.jpg" />
                <img u="thumb" src="images/travel/thumb-04.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/05.jpg" />
                <img u="thumb" src="images/travel/thumb-05.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/06.jpg" />
                <img u="thumb" src="images/travel/thumb-06.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/07.jpg" />
                <img u="thumb" src="images/travel/thumb-07.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/08.jpg" />
                <img u="thumb" src="images/travel/thumb-08.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/09.jpg" />
                <img u="thumb" src="images/travel/thumb-09.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/10.jpg" />
                <img u="thumb" src="images/travel/thumb-10.jpg" />
            </div>

            <div>
                <img u="image" src="images/travel/11.jpg" />
                <img u="thumb" src="images/travel/thumb-11.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/12.jpg" />
                <img u="thumb" src="images/travel/thumb-12.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/13.jpg" />
                <img u="thumb" src="images/travel/thumb-13.jpg" />
            </div>
            <div>
                <img u="image" src="images/travel/14.jpg" />
                <img u="thumb" src="images/travel/thumb-14.jpg" />
            </div>
        </div>
        
        
        <!-- Thumbnail Navigator Skin Begin -->
        <div u="thumbnavigator" class="jssort07" style="position: absolute; width: 444px; height: 441px; left: 0px; bottom: 0px; overflow: hidden; ">
            <div style=" background-color: #000; filter:alpha(opacity=30); opacity:.3; width: 100%; height:100%;"></div>
            <!-- Thumbnail Item Skin Begin -->
       <style>
                /* jssor slider thumbnail navigator skin 07 css */
                /*
                .jssort07 .p            (normal)
                .jssort07 .p:hover      (normal mouseover)
                .jssort07 .pav          (active)
                .jssort07 .pav:hover    (active mouseover)
                .jssort07 .pdn          (mousedown)
                */
                .jssort07 .i {
                    position: absolute;
                    top: 0px;
                    left: 0px;
                    width: 50px;
                    height: 40px;
                    filter: alpha(opacity=80);
                    opacity: .8;
                }

                .jssort07 .p:hover .i, .jssort07 .pav .i {
                    filter: alpha(opacity=100);
                    opacity: 1;
                }

                .jssort07 .o {
                    position: absolute;
                    top: 0px;
                    left: 0px;
                    width: 50px;
                    height: 40px;
                    border: 1px solid #000;
                    transition: border-color .6s;
                    -moz-transition: border-color .6s;
                    -webkit-transition: border-color .6s;
                    -o-transition: border-color .6s;
                }

                * html .jssort07 .o {
                    /* ie quirks mode adjust */
                    width /**/: 50px;
                    height /**/: 40px;
                }

                .jssort07 .pav .o, .jssort07 .p:hover .o {
                    border-color: #fff;
                }

                .jssort07 .pav:hover .o {
                    border-color: #0099FF;
                }

                .jssort07 .p:hover .o {
                    transition: none;
                    -moz-transition: none;
                    -webkit-transition: none;
                    -o-transition: none;
                }
            </style>
            <div u="slides" style="cursor: move;">
                <div u="prototype" class="p" style="POSITION: absolute; WIDTH: 50px; HEIGHT: 40px; TOP: 0; LEFT: 0;">
                    <div u="thumbnailtemplate" class="i" style="position:absolute;"></div>
                    <div class="o">
                    </div>
                </div>
            </div>
            <!-- Thumbnail Item Skin End -->
            <!-- Arrow Navigator Skin Begin -->
           <style>
                    /* jssor slider arrow navigator skin 11 css */
                    /*
                .jssora11l              (normal)
                .jssora11r              (normal)
                .jssora11l:hover        (normal mouseover)
                .jssora11r:hover        (normal mouseover)
                .jssora11ldn            (mousedown)
                .jssora11rdn            (mousedown)
                */
                    .jssora11l, .jssora11r, .jssora11ldn, .jssora11rdn {
                        position: absolute;
                        cursor: pointer;
                        display: block;
                        background: url(../img/a11.png) no-repeat;
                        overflow: hidden;
                    }

                    .jssora11l {
                        background-position: -11px -41px;
                    }

                    .jssora11r {
                        background-position: -71px -41px;
                    }

                    .jssora11l:hover {
                        background-position: -131px -41px;
                    }

                    .jssora11r:hover {
                        background-position: -191px -41px;
                    }

                    .jssora11ldn {
                        background-position: -251px -41px;
                    }

                    .jssora11rdn {
                        background-position: -311px -41px;
                    }
            </style>
            <!-- Arrow Left -->
            <span u="arrowleft" class="jssora11l" style="width: 37px; height: 37px; top: 123px; left: 8px;">
            </span>
            <!-- Arrow Right -->
            <span u="arrowright" class="jssora11r" style="width: 37px; height: 37px; top: 123px; right: 8px">
            </span>
            <!-- Arrow Navigator Skin End -->
        </div>
        
        <!-- Trigger -->
    </div>
   



<!--ending of slider -->
<!--<a href="#"><img class="img-responsive" src="images/user.png" /></a>-->

<p class="set-thumb">Deceased's Profile Name</p>
<span class="set-band">Date: Oct 2,1869-Jan 30,1948</span>
<form>
<input class="inputs" type="text"/><input class="inputs" type="text"/>
<input class="inputs" type="text"/><input class="inputs" type="text"/>
<input class="inputs" type="text"/><input class="inputs" type="text"/>
<input class="inputs" type="text"/><input class="inputs" type="text"/>
</form>
<div class="back_border">Add Audio, Video and Images</div>
<select class="demoa form-controls">
  <option>Rest in peace</option>
  <option>Rest in peace</option>
  <option>Rest in peace</option>
  <option>Rest in peace</option>
  <option>Rest in peace</option>
</select>
<div class="set-img"><img src="images/adminimage.jpg" /><img src="images/adminimage.jpg" /><img src="images/adminimage.jpg" /></div>
<p class="set-thumbs">Created by: Rajiv Bhatia</p>
<span class="set-bands">Privacy Setting: Public</span>
</div>
<div class="col-md-8 border-left">
<ul role="tablist" class="nav nav-tabs navs" id="myTab">
        <li class="active" role="presentation"><a aria-expanded="true" aria-controls="home" data-toggle="tab" role="tab" id="home-tab" href="#home">Info</a></li>
        <li role="presentation" class=""><a aria-controls="profile" data-toggle="tab" id="profile-tab" role="tab" href="#profile" aria-expanded="false">Edu</a></li>
        <li role="presentation" class=""><a aria-controls="profile" data-toggle="tab" id="profile-tab" role="tab" href="#family" aria-expanded="false">Family</a></li>
        <li role="presentation" class=""><a aria-controls="profile" data-toggle="tab" id="profile-tab" role="tab" href="#profile" aria-expanded="false">Guestbook</a></li>
        <li role="presentation" class=""><a aria-controls="profile" data-toggle="tab" id="profile-tab" role="tab" href="#profile" aria-expanded="false">Tributes</a></li>
        <li role="presentation" class=""><a aria-controls="profile" data-toggle="tab" id="profile-tab" role="tab" href="#profile" aria-expanded="false">Donate</a></li>
        <li role="presentation" class=""><a aria-controls="profile" data-toggle="tab" id="profile-tab" role="tab" href="#profile" aria-expanded="false">More...</a></li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div aria-labelledby="home-tab" id="home" class="tab-pane fade active in" role="tabpanel">
       <div class="border-set">
       <div class="col-md-6 set-space" style="padding:10px;">
       <form class="form-horizontal" action="" method="post">
  <style>
  .form-group{
    margin-top:10px !important;
  }
  </style>
             <div class="form-group">
                 <label class="col-sm-2 control-label">Salutation</label>
               <div class="col-sm-10">
                    <select name="user[salutation]" class="form-control">
                     <option value="mr">Mr.</option>
                     <option value="mrs">Mrs.</option>
                     <option value="ms">Ms.</option>
                    </select>
               </div>
            </div>
          
                <div class="form-group">
                     <label class="col-sm-2 control-label">First Name</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[first_name]" class="form-control" placeholder="First Name" />
                   </div>
                </div>
          
               <div class="form-group">
                     <label class="col-sm-2 control-label">Last Name</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[last_name]" class="form-control" placeholder="Last Name" />
                   </div>
                </div>
                <div class="form-group">
                     <label class="col-sm-2 control-label">Middle Name</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[middle_name]" class="form-control" placeholder="Middle Name" />
                   </div>
                </div>
            
           
             <div class="form-group">
                     <label class="col-sm-2 control-label">Aka</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[aka]" class="form-control" />
                   </div>
                </div>
                <div class="form-group">
                   <label class="col-sm-2 control-label">Gender</label>
                   <label class="radio-inline">
                        <input type="radio" name="user[gender]" value="male" />Male
                   </label>
                  <label class="radio-inline">
                        <input type="radio" name="user[gender]" value="female"  />Female
                  </label>
                </div>
           
               <div class="form-group">
                     <label class="col-sm-2 control-label">Resident of</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[resident]" class="form-control" />
                   </div>
                </div>
            
               <div class="form-group">
                     <label class="col-sm-2 control-label">Occupation</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[occupation]" class="form-control" />
                   </div>
                </div>
            
      
       </div>
       <div class="col-md-6 set-space1" >
       
           <div class="form-group">
                     <label class="col-sm-2 control-label">Caste</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[caste]" class="form-control" />
                   </div>
                </div>
           
               <div class="form-group">
                     <label class="col-sm-2 control-label">Gotra</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[gotra]" class="form-control" />
                   </div>
                </div>
            
               <div class="form-group">
                     <label class="col-sm-2 control-label">POD</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[death_place]" class="form-control" />
                   </div>
                </div>
             <div class="form-group">
                     <label class="col-sm-2 control-label">COD</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[death_cause]" class="form-control" />
                   </div>
                </div>
 
             <div class="form-group">
                     <label class="col-sm-2 control-label">TOD</label>
                   <div class="col-sm-9">
                        <input type="text" name="user[death_time]" id="deathTime" class="form-control" />
                   </div>
                </div>
             <div class="form-group">
                     <label class="col-sm-2 control-label">DOB</label>
                   <div class="col-sm-9">
                        <input type="text" name="user[date_of_birth]" id="dateOfBirth" class="form-control" />
                   </div>
                </div>
           
               <div class="form-group">
                     <label class="col-sm-2 control-label">DOD</label>
                   <div class="col-sm-9">
                        <input type="text" name="user[date_of_death]" id="dateOfDeath" class="form-control" />
                   </div>
                </div>
            
               <div class="form-group">
                     <label class="col-sm-2 control-label">Age(Approx)</label>
                   <div class="col-sm-9">
                        <input type="text" name="user[age]" class="form-control" />
                   </div>
                </div>
       </div>
       <div class="clearfix"></div>
       </div>
	   
	   <div class="border-sets">
       <div class="col-md-6"><p class="set-thumb">Obituary</p>
       <p class="set-thumbe">We regret to inform you that this person has passedway.</p>
       </div>
	   <div class="col-md-6">
       <div class="set-back border-full">Select from other style and language</div>
       <p class="custom-style">Custom it <span class="custom-span">Read more...</span></p>
       </div>
	   <div class="clearfix"></div>
       </div>
	   
	   <div class="border-sets">
	   <div class="floatl">
       <div class="event-new">
	   <div class="well well-sm wells">Event Cal</div>
	   </div>
	   <div class="event-news">
	   <div class="well well-sm wells">Alerts</div>
	   </div>
	   </div>
	   <div class="position-img"><img src="images/icon.png"></div>
	   <div class="floatl">
       <div class="event-new1">
	   <div class="well well-sm wells">Day by day events</div>
	   </div>
	   <div class="event-news1">
	   <div class="well well-sm wells">Car Pool</div>
	   </div>
	   </div>
	   
	   <div class="position-imgs"><img src="images/icon.png"></div>
	   <div class="floatl">
       <div class="event-new2">
	   <div class="well well-sm wells">Shared Tasks</div>
	   </div>
	   <div class="event-news2">
	   <div class="well well-sm wells">Meet &amp; Greet Points</div>
	   </div>
	   </div>
	   
	   <div class="clearfix"></div>
       </div>
	   
	   <div>
       <a href="#" class="first-button">Tools</a>
       <button type="submit" class="second-button">Save to my account</button>
       <a class="third-button" href="#">Send</a></div>
	   </form>
      </div>
       <!-- edu tab starting -->
      <div aria-labelledby="profile-tab" id="profile" class="tab-pane fade" role="tabpanel">
       <div class="border-set">
       <div class="col-md-8">
        <!-- edu form -->
         <form class="form-horizontal" style="margin-top: 20px;" method="post" action="<?php echo $this->url('application/default',array('controller'=>'index','action'=>'edu')); ?>">
            <div class="form-group">
                     <label class="col-sm-2 control-label">School</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[school]" class="form-control" />
                   </div>
                </div>
             <div class="form-group">
                     <label class="col-sm-2 control-label">College</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[college]" class="form-control" />
                   </div>
                </div>
                 <div class="form-group">
                     <label class="col-sm-2 control-label">University</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[university]" class="form-control" />
                   </div>
                </div>
                <div class="form-group">
                     <label class="col-sm-2 control-label">Others</label>
                   <div class="col-sm-10">
                        <input type="text" name="user[others]" class="form-control" />
                   </div>
                </div>
         
        <!-- end edu form -->

       </div>
       <div class="clearfix"></div>
    </div>
     <div>
     <a href="#" class="first-button">Tools</a>
     <button class="second-button" type="submit" >Save to my account</button>
     <a class="third-button">Send</a></div>
      </form>
      </div>
      <!-- edu tab ending -->
      
      <!-- start family Tab -->
      <div aria-labelledby="dropdown1-tab" id="family" class="tab-pane fade" role="tabpanel"> 
        <div class="border-set">
            <div class="col-md-12">
            <p>Survived By</p>
            <form class="form-inline" method="post" action="<?php echo $this->url('application/default',array('controller'=>'index','action'=>'edu')); ?>">
            <div class="border-sets">
                <!-- family Form -->
               
                  <div class="form-group" style="margin:5px;">
                    <select class="form-control" >
                        <option>Grand Father</option>
                        <option>Grand Mother</option>
                        <option>Father</option>
                        <option>Mother</option>
                        <option>Sister</option>
                        <option>Brother</option>
                    </select>
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="first_name" class="form-control" placeholder="First Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="last_name" class="form-control" placeholder="Last Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="middle_name" class="form-control" placeholder="Middle Name" />
                  </div>
                  <br />
                  <div class="form-group">
                    <select class="form-control" style="margin: 5px;">
                        <option>Grand Father</option>
                        <option>Grand Mother</option>
                        <option>Father</option>
                        <option>Mother</option>
                        <option>Sister</option>
                        <option>Brother</option>
                    </select>
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="first_name" class="form-control" placeholder="First Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="last_name" class="form-control" placeholder="Last Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="middle_name" class="form-control" placeholder="Middle Name" />
                  </div>
                  <br />
                  <div class="form-group" style="margin: 5px;">
                    <select class="form-control" >
                        <option>Grand Father</option>
                        <option>Grand Mother</option>
                        <option>Father</option>
                        <option>Mother</option>
                        <option>Sister</option>
                        <option>Brother</option>
                    </select>
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="first_name" class="form-control" placeholder="First Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="last_name" class="form-control" placeholder="Last Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="middle_name" class="form-control" placeholder="Middle Name" />
                  </div>
                  </div>
                  <p>Predeceased By</p>
                      <div class="border-sets">
                          <div class="form-group" style="margin:5px;">
                    <select class="form-control" >
                        <option>Grand Father</option>
                        <option>Grand Mother</option>
                        <option>Father</option>
                        <option>Mother</option>
                        <option>Sister</option>
                        <option>Brother</option>
                    </select>
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="first_name" class="form-control" placeholder="First Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="last_name" class="form-control" placeholder="Last Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="middle_name" class="form-control" placeholder="Middle Name" />
                  </div>
                  <br />
                  <div class="form-group">
                    <select class="form-control" style="margin: 5px;">
                        <option>Grand Father</option>
                        <option>Grand Mother</option>
                        <option>Father</option>
                        <option>Mother</option>
                        <option>Sister</option>
                        <option>Brother</option>
                    </select>
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="first_name" class="form-control" placeholder="First Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="last_name" class="form-control" placeholder="Last Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="middle_name" class="form-control" placeholder="Middle Name" />
                  </div>
                  <br />
                  <div class="form-group" style="margin: 5px;">
                    <select class="form-control" >
                        <option>Grand Father</option>
                        <option>Grand Mother</option>
                        <option>Father</option>
                        <option>Mother</option>
                        <option>Sister</option>
                        <option>Brother</option>
                    </select>
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="first_name" class="form-control" placeholder="First Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="last_name" class="form-control" placeholder="Last Name" />
                  </div>
                  <div class="form-group" style="margin: 5px;">
                   <input type="middle_name" class="form-control" placeholder="Middle Name" />
                  </div>
                      
                      </div>
                
                
                
                <!-- end family Form -->
             </div>
             <div class="clearfix"></div>
       </div>
	   
	   
	   <div><a href="#" class="first-button">Tools</a>
       <button type="submit" class="second-button">Save to my account</button>
       <a class="third-button">Send</a></div>
      
      </form>
      </div>
      <!-- end family Tab -->
      <div aria-labelledby="dropdown2-tab" id="dropdown2" class="tab-pane fade" role="tabpanel">
         <div class="border-set">
       <div class="col-md-6 set-space">
      <ul class="under-list">
      <li><a href="#35">first</a></li>
       <li><a href="#">Second</a></li>
        <li><a href="#">Third</a></li>
         <li><a href="#">Fourth</a></li>
          <li><a href="#">Fifth</a></li>
		   <li><a href="#">Third</a></li>
        
      </ul>
       </div>
       <div class="col-md-6 set-space1">
        <ul class="under-lists">
      <li><a href="#35">first</a></li>
       <li><a href="#">Second</a></li>
        <li><a href="#">Third</a></li>
         <li><a href="#">Fourth</a></li>
          <li><a href="#">Fifth</a></li>
          <li><a href="#">Sixth</a></li>
         <li><a href="#">Seventh</a></li>
          <li><a href="#">Eighth</a></li>
      </ul>
       </div>
       <div class="clearfix"></div>
       </div>
	   
	   <div class="border-sets">
       <div class="col-md-6"><p class="set-thumb">Obituary</p>
       <p class="set-thumbe">We regret to inform you that this person has passedway.</p>
       </div>
	   <div class="col-md-6">
       <div class="set-back border-full">Select from other style and language</div>
       <p class="custom-style">Custom it <span class="custom-span">Read more...</span></p>
       </div>
	   <div class="clearfix"></div>
       </div>
	   
	   <div class="border-sets">
	   <div class="floatl">
       <div class="event-new">
	   <div class="well well-sm wells">Event Cal</div>
	   </div>
	   <div class="event-news">
	   <div class="well well-sm wells">Alerts</div>
	   </div>
	   </div>
	   <div class="position-img"><img src="images/icon.png"></div>
	   <div class="floatl">
       <div class="event-new1">
	   <div class="well well-sm wells">Day by day events</div>
	   </div>
	   <div class="event-news1">
	   <div class="well well-sm wells">Car Pool</div>
	   </div>
	   </div>
	   
	   <div class="position-imgs"><img src="images/icon.png"></div>
	   <div class="floatl">
       <div class="event-new2">
	   <div class="well well-sm wells">Shared Tasks</div>
	   </div>
	   <div class="event-news2">
	   <div class="well well-sm wells">Meet &amp; Greet Points</div>
	   </div>
	   </div>
	   
	   <div class="clearfix"></div>
       </div>
	   
	   <div><a href="#" class="first-button">Tools</a><a class="second-button">Save to my account</a><a class="third-button">Send</a></div>
      </div>
    </div>
</div>
<div class="clearfix"></div>
</div>
<script>
$(document).ready(function(){
    $('#deathTime').datetimepicker({datepicker:false,format:'H:i'});
    $('#dateOfBirth').datetimepicker({timepicker:false,format:'d-m-Y'});
    $('#dateOfDeath').datetimepicker({timepicker:false,format:'d-m-Y'});
})


</script>
