<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit List')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('find' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/donation', array('action' => 'edit', 'id' => $this->donation->id)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formLabel($form->get('category_id'));
            echo $this->formSelect($form->get('category_id'));
            echo $this->formRow($form->get('name'));
            echo $this->formRow($form->get('address')); 
            echo $this->formRow($form->get('amount'));
            echo $this->formLabel($form->get('photo'));
            echo $this->formFile($form->get('photo'));
            ?>
            <img src="<?php echo $this->basePath('/../module/Admin/assets/donation/thumb/'.$this->donation->id.'_'.$this->donation->photo); ?>" width="72" height="72"/>
            <?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>