<?php
$this->headScript()->prependFile($this->basePath() . '/assets/lib/NicEditor/nicEdit.js');
 ?>
<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit Gothra')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('gothra' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/gothra', array('action' => 'edit', 'id' => $this->id)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('title'));          
            echo $this->formRow($form->get('content'));           
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
<?php $this->inlineScript()->captureStart() ?>
$(function() { var nicEditors = new nicEditor({iconsPath : '../../../assets/lib/NicEditor/nicEditorIcons.gif'}).panelInstance('nicedit'); });
<?php $this->inlineScript()->captureEnd() ?>
