<?php
$this->headScript()->prependFile($this->basePath() . '/assets/lib/NicEditor/nicEdit.js');
 ?>
<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit Page')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('traditionals' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
           <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/rituals', array('action' => 'edit','id'=>$this->id)));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formRow($form->get('traditional_id'));
             echo '<fieldset>';
            echo $this->formCollection($form->get('content'));
            echo '</fieldset>';
            ?>           
            <div>
                <span onclick="add_category()">Add a day</span>
            </div>
            <?php
            echo '<br/>';
            echo $this->formRow($form->get('cultural'));
            echo $this->formRow($form->get('preference'));
            echo $this->formRow($form->get('practical'));
            echo $this->formRow($form->get('interfaith'));
            echo $this->formRow($form->get('other'));
            echo $this->formRow($form->get('id'));
            echo $this->formRow($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>


<span class="template" data-template='<fieldset><legend>Content</legend><label><span>__title__</span><textarea class="form-control" name="content[__index__][content]"></textarea></label></fieldset>'></span>

<script>

                        
                    function add_category() {
                       var currentCount = $('form > fieldset > fieldset').length;
                        day = currentCount+1;                       
                        var template = $('.template').data('template');
                        template = template.replace(/__index__/g, currentCount+1);
                        template = template.replace(/__title__/g, 'Day ' + day);
                        $('form > fieldset').append(template);

                        return false;
                    }
</script>
                    <?php $this->inlineScript()->captureStart() ?>
<?php $this->inlineScript()->captureEnd() ?>
