<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SecureChat ' . $this->translate('SecureChat'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/img/securechat.ico'))
                ->prependStylesheet($this->basePath() . '/assets/lib/bootstrap/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/assets/css/main.css')
                ->prependStylesheet($this->basePath() . '/assets/lib/Font-Awesome/css/font-awesome.css');
        ?>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/assets/lib/bootstrap/js/bootstrap.js')
                ->prependFile('http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.js');
        ?>
    </head>
    <body>
        
        <div id="wrap">
            <?php echo $this->content; ?>

            <!-- Scripts -->
            <footer>
                <?= $this->partial('layout/footer'); ?>
            </footer>

            <?php echo $this->inlineScript(); ?>
        </div>
        <div class="modal"><!-- Place at bottom of page --></div>
    </body>

</html>
