
<p>&copy; 2014-<?php echo date("Y");?>  SecureChat.in <?php echo $this->translate('All rights reserved.') ?></p>
<!--

<script>
$(document).ready(function()
{ 
       $(document).bind("contextmenu",function(e){
              return false;
       }); 
})

    document.onkeydown = function (cc) {
    if(cc.which == 85){
    return false;
    }
    if(cc.which == 80){
    return false;
    }
    }
    </script>
-->
