<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SecureChat')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/img/securechat.ico'))
                ->prependStylesheet($this->basePath() . '/assets/lib/bootstrap/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/assets/css/main.css')
                
                ->prependStylesheet($this->basePath() . '/assets/lib/Font-Awesome/css/font-awesome.css')
                ->prependStylesheet($this->basePath() . '/assets/lib/fancybox/jquery.fancybox.css');
        ?>
        
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/assets/lib/bootstrap/js/bootstrap.js')
                ->prependFile($this->basePath() . '/assets/lib/fancybox/jquery.fancybox.js')
                ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js')
               
        ?>
      </head>
    <body>
        <div id="top" style=" border-bottom: 1px solid cornflowerblue;padding: 10px 0 0;width: 100%;" > <!--style="width:87%;padding-left:13.5%;"-->
            <div class="top_bg" style="background:#fff">
                <div id="top_main" >
                    <?php echo $this->partial('layout/top_menu'); ?>
                </div>
            </div>
        </div>
        <div class="main" >
            <div class="welcomemsg" style="display: none">

                <p><?php echo $this->translate('Our mission is to help global Hindu families and communities cope with end of life issues efficiently,compassionately and collaboratively'); ?></p>

            </div>

            <div class="socialmedia">
                <?php $url = 'http://www.securechat.in'; ?>
                <ul>
                    <li><a href="<?php echo $this->basePath('/faq'); ?>" class="">Faq</a></li>
                    <li>
                        <a href="#" class="">Share</a>
                        <ul class="share">
                            <li>
                                <a target="_blank" href="http://www.facebook.com/sharer.php?u=<?php echo $url; ?>&t=SecureChat">Facebook</a>
                            </li>
                            <li>
                                <a target="_blank" href="http://twitter.com/share?text=SecureChat&url=<?php echo $url; ?>">
                                    Twitter
                                </a>
                            </li>
                            <li><a href="http://www.linkedin.com/shareArticle?url=<?php echo $url; ?>&amp;title=SecureChat" target="_blank">
                                  LinkedIn
                                </a>
                            </li>                           
                            <li>
                                <a target="_blank" href="https://plus.google.com/share?url=<?php echo $url; ?>">
                                    Google
                                </a>
                            </li>                              
                        </ul>

                    </li>
                    <li><a href="#demo" class="fancybox">Demo</a></li>
                </ul>
            </div>

            <?php  echo $this->content;  ?>  
            
            <footer>
           
              <?php echo $this->partial('layout/footer'); ?>
            </footer>
        </div>

<div id="demo" style="display:none;width:500px">   
   
</div>  
        <?php echo $this->inlineScript(); ?>

    </body>

</html>
