<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('SecureChat'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/img/securechat.ico'))
                ->prependStylesheet($this->basePath() . '/assets/lib/bootstrap/css/bootstrap.css')
                ->prependStylesheet($this->basePath() . '/assets/lib/magic/magic.css')
                ->prependStylesheet($this->basePath() . '/assets/css/main.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
        ?>
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/json.js')
                ->prependFile($this->basePath() . '/assets/lib/bootstrap/js/bootstrap.js')
                ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js');
        ?>
    </head>
    <body>
        <div id="top"><?= $this->partial('layout/top_menu'); ?></div>
        <div class="container">
            <?php echo $this->content; ?>          
        </div>
        <!-- Scripts -->
        <footer>
            <?= $this->partial('layout/footer'); ?>
        </footer>

        <?php echo $this->inlineScript(); ?>

    </body>

    <script>
        var newClass = window.location.href;
        newClass = newClass.substring(newClass.lastIndexOf('/') + 1);
        $('body').addClass(newClass);
    </script>
</html>
