<?php 

$sm = $this->getHelperPluginManager()->getServiceLocator();
$service = $sm->get('zfcuser_user_service');
$id = $service->getAuthService()->getIdentity()->getId();

?>

    <ul>        
        <li><a href="<?php echo $this->basePath('/user/change-email'); ?>">Profile</a></li>  
        <li><a href="<?php echo $this->basePath('/user/change-password'); ?>">Change Password</a></li> 
        <li><a href="<?php echo $this->basePath('/accounts'); ?>">Connected Account</a></li>  
        <li><a href="<?php echo $this->basePath('/delete-account/'.$id); ?>">Delete Account</a></li>  
    </ul>

