<?php
$this->headLink()->prependStylesheet($this->basePath() . '/assets/lib/CLEditor1_4_3/jquery.cleditor.css');

$this->headScript()->prependFile($this->basePath() . '/assets/lib/CLEditor1_4_3/jquery.cleditor.min.js');
 ?>
<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit Page')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('cms' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/cms', array('action' => 'edit', 'id' => $this->id)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('title'));
            echo $this->formRow($form->get('url_key'));
            echo $this->formRow($form->get('content'));
            echo $this->formSelect($form->get('is_active'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
<?php $this->inlineScript()->captureStart() ?>
$(function() {    $("textarea").cleditor(); });
<?php $this->inlineScript()->captureEnd() ?>
