<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit Language')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('languages' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/language', array('action' => 'edit', 'id' => $this->id)));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('name'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>