
    <div class="media user-media">
        <a class="user-link" href="">
            <img class="media-object img-thumbnail user-img" alt="User Picture" src="<?php echo $this->basePath(); ?>/assets/img/user.gif">
            <span class="label label-danger user-label">16</span>
        </a>

        <div class="media-body">
            <h5 class="media-heading">Archie</h5>
            <ul class="list-unstyled user-info">
                <li><a href="">Administrator</a></li>
                <li>Last Access : <br>
                    <small><i class="fa fa-calendar"></i> 16 Mar 16:32</small>
                </li>
            </ul>
        </div>
    </div>
    <!-- #menu -->
    <ul id="menu" class="collapse">
        <li class="nav-header">Menu</li>
        <li class="nav-divider"></li>
        <li><a class="<?= $this->dashboard; ?>" href="<?php echo $this->basePath('/admin'); ?>"><i class="fa fa-dashboard"></i>Dashboard</a></li>
        <li><a class="<?= $this->users; ?>" href="<?php echo $this->basePath('/admin/users'); ?>"><i class="fa fa-user-md"></i>Users</a></li>
        <li><a class="<?= $this->category; ?>" href="<?php echo $this->basePath('/admin/category'); ?>"><i class="fa fa-th-list"></i>Category</a></li>
        <li><a class="<?= $this->tasks; ?>" href="<?php echo $this->basePath('/admin/tasks'); ?>"><i class="fa fa-tasks"></i>Tasks</a></li>
        <li><a class="<?= $this->cms; ?>" href="<?php echo $this->basePath('/admin/cms'); ?>"><i class="fa fa-tasks"></i>Cms</a></li>
        <li><a class="<?= $this->faq; ?>" href="<?php echo $this->basePath('/admin/faq'); ?>"><i class="fa fa-tasks"></i>FAQ</a></li>
        <li><a class="<?= $this->templates; ?>" href="<?php echo $this->basePath('/admin/templates'); ?>"><i class="fa fa-tasks"></i>Templates</a></li>
        
        <li class="panel <?= $this->find; ?>">
            <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#component-nav">
                <i class="fa fa-tasks"></i> Cremation Plan
                <span class="pull-right">
                    <i class="fa fa-angle-left"></i>
                </span>
            </a>
            <ul class="collapse" id="component-nav">
                 <li>
                            <a  href="<?php echo $this->basePath('/admin/cremation-templates'); ?>"><i class="fa fa-angle-right"></i>
                                Templates
                            </a> 
                        </li>
                        <li>
                            <a  href="<?php echo $this->basePath('/admin/language'); ?>"><i class="fa fa-angle-right"></i>
                                Languages
                            </a> 
                        </li>
                        <li>
                            <a  href="<?php echo $this->basePath('/admin/traditionals'); ?>"><i class="fa fa-angle-right"></i>
                                Traditionals
                            </a> 
                        </li>
                        <li>
                            <a  href="<?php echo $this->basePath('/admin/rituals'); ?>"><i class="fa fa-angle-right"></i>
                                Rituals
                            </a> 
                        </li>
                        <li>
                            <a  class="<?= $this->protect; ?>" href="<?php echo $this->basePath('/admin/protect'); ?>"><i class="fa fa-angle-right"></i>
                                Protect
                            </a> 
                        </li>
                        <li>
                            <a  href="<?php echo $this->basePath('/admin/gothra'); ?>"><i class="fa fa-angle-right"></i>
                                Gotra
                            </a> 
                        </li>
                        <li>
                            <a  href="<?php echo $this->basePath('/admin/hindusim'); ?>"><i class="fa fa-angle-right"></i>
                                Hinduism
                            </a> 
                        </li>
                        
               
               <li>
                            <a  href="<?php echo $this->basePath('/admin/impacts'); ?>"><i class="fa fa-angle-right"></i>
                                Impacts
                            </a> 
                        </li>
                <li class="<?= $this->find; ?>"><a  href="<?php echo $this->basePath('/admin/find'); ?>"><i class="fa fa-angle-right"></i>
                        Find</a></li>
                <li class=""><a href="<?php echo $this->basePath('/admin/products'); ?>"><i class="fa fa-angle-right"></i> Purchase </a>
                </li>
<li class=""><a href="<?php echo $this->basePath('/admin/garlands'); ?>"><i class="fa fa-angle-right"></i> Garlands </a>
                </li>
            </ul>
        </li>
        <li class="panel <?= $this->shopping; ?>">
            <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#shopping-nav">
                <i class="fa fa-tasks"></i> Shopping
                <span class="pull-right">
                    <i class="fa fa-angle-left"></i>
                </span>
            </a>
            <ul class="collapse" id="shopping-nav">
                 <li>
                            <a  href="<?php echo $this->basePath('/admin/shopping-category'); ?>"><i class="fa fa-angle-right"></i>
                                Categories
                            </a> 
                        </li>
                        <li>
                            <a  href="<?php echo $this->basePath('/admin/shopping-item'); ?>"><i class="fa fa-angle-right"></i>
                                Items
                            </a> 
                        </li>
                
            </ul>
        </li>
        <li class="panel <?= $this->donation; ?>">
            <a href="#" data-parent="#menu" data-toggle="collapse" class="accordion-toggle" data-target="#donation-nav">
                <i class="fa fa-tasks"></i> Donation
                <span class="pull-right">
                    <i class="fa fa-angle-left"></i>
                </span>
            </a>
            <ul class="collapse" id="donation-nav">
                
                        <li>
                            <a  href="<?php echo $this->basePath('/admin/donation-cause'); ?>"><i class="fa fa-angle-right"></i>
                                Cause
                            </a> 
                        </li>
                         <li>
                            <a  href="<?php echo $this->basePath('/admin/donation-charity'); ?>"><i class="fa fa-angle-right"></i>
                                Charities
                            </a> 
                        </li>
                
            </ul>
        </li>
        <li><a class="<?= $this->preplanning; ?>" href="<?php echo $this->basePath('/admin/pre-planning'); ?>"><i class="fa fa-tasks"></i>Pre Planning</a></li>
       
       
    </ul>
