
<div id="top"><?= $this->partial('layout/admin_top_menu', array('tittle' => 'Edit Question')); ?></div>
<div id="left"> <?= $this->partial('layout/left-menu', array('faq' => 'active')); ?></div> 
<div id="content"> 
    <div class="outer">
        <div class="inner">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin/faq', array('action' => 'edit', 'id' => $this->id)));
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
             echo $this->formRow($form->get('category_id'));  
            echo $this->formRow($form->get('question'));           
            echo $this->formRow($form->get('answer'));
             echo $this->formLabel($form->get('is_active'));
            echo $this->formSelect($form->get('is_active'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
