<div class="header-bottom">
<div class="col-md-4">
<a class="logo-top" href="#">Cremation Planning <i class="fa fa-chevron-right"></i></a>
<a class="main-slide" href="#">Announce</a>
</div>

<div class="col-md-4">
	<!--<div class="button-radio">
	<input type="radio" class="css-checkbox" id="radiofirst" name="radiog_lite" checked="checked" >
	<label class="css-label1 radGroup1" for="radiofirst">Create New</label>

	<input type="radio" class="css-checkbox" id="radiosecond" name="radiog_lite">
	<label class="css-label1 radGroup1" for="radiosecond">My Account</label>
	</div>-->
</div>

<div class="col-md-4">
<div class="floatr border-full">
<a class="alls first" href="#">FAQ</a><a class="alls second" href="#">Demo</a><a class="alls third" href="#">Share</a>
</div>
</div>

<div class="clearfix"></div>
</div>

<div class="section-band">
<div class="col-md-4 border-right text-center">
<a href="#"><img class="img-responsive" src="images/user.png" /></a>
<p class="set-thumb">Deceased's Profile Name</p>
<span class="set-band">Date: Oct 2,1869-Jan 30,1948</span>
<form>
<input class="inputs" type="text"/><input class="inputs" type="text"/><input class="inputs" type="text"/><input class="inputs" type="text"/><input class="inputs" type="text"/><input class="inputs" type="text"/><input class="inputs" type="text"/><input class="inputs" type="text"/>
</form>
<div class="back_border">Add Audio, Video and Images</div>
<select class="demoa form-controls">
  <option>Rest in Peace</option>
		  <option>R.I.P.</option>
		  <option>We miss you</option>
		  <option>Love you Forever</option>
		  <option>You won't be forgotten</option>
		  <option>You will always be in our hearts</option>
		  <option>Whereever you are, we love you</option>
</select>
<div class="set-img"><img src="images/adminimage.jpg" /><img src="images/adminimage.jpg" /><img src="images/adminimage.jpg" /></div>
<p class="set-thumbs">Created by: Rajiv Bhatia</p>
<span class="set-bands">Privacy Setting: Public</span>
</div>
<div class="col-md-8 border-left">
<ul role="tablist" class="nav nav-tabs navs" id="myTab">
      <li class="active" role="presentation"><a aria-expanded="true" aria-controls="home" data-toggle="tab" role="tab" id="home-tab" href="#home">Achivements &amp; Awards</a></li>
      <li role="presentation" class=""><a aria-controls="profile" data-toggle="tab" id="profile-tab" role="tab" href="#profile" aria-expanded="false">Personal Honors</a></li>
	   <li role="presentation" class=""><a aria-controls="family" data-toggle="tab" id="family-tab" role="tab" href="#family" aria-expanded="false">Digital footprints and links</a></li>
	    <li role="presentation" class=""><a aria-controls="guestbook" data-toggle="tab" id="guestbook-tab" role="tab" href="#guestbook" aria-expanded="false">Back to Info</a></li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div aria-labelledby="home-tab" id="home" class="tab-pane fade active in" role="tabpanel">
      
	  <div class="border-set">
       <div class="col-md-12">
       <div class="set-form">
      
	  <form>
	  <div class="form-group">
    <label for="exampleInputPassword1">Professionals</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">personal</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  </form>

	  
      </div>
       </div>
       <div class="clearfix"></div>
       </div>
	   
	    <div><a class="toolButton" href="#">Tools</a><a class="saveButton">Save to my account</a><a class="sendButton">Send</a></div>
	   
      </div>
      <div aria-labelledby="profile-tab" id="profile" class="tab-pane fade" role="tabpanel">
	  
	 
	   <div class="border-set">
       <div class="col-md-12">
       <div class="set-form">
      
	  <form>
	  <div class="form-group">
    <label for="exampleInputPassword1">Qualities: Best Singer, Most helpful</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Relationship: My Favourite Uncle</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Influence: Fan of your Music</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  </form>

	  
      </div>
       </div>
       <div class="clearfix"></div>
       </div>
	   
	    <div><a class="toolButton" href="#">Tools</a><a class="saveButton">Save to my account</a><a class="sendButton">Send</a></div>
       
      </div>
	  
	  
	  
	  <div aria-labelledby="family-tab" id="family" class="tab-pane fade" role="tabpanel">
	  
	   <div class="border-set">
       <div class="col-md-12">
       <div class="set-form">
      
	  <form>
	  <div class="form-group">
    <label for="exampleInputPassword1">Links</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">References</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Social Sites</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  </form>

	  
      </div>
       </div>
       <div class="clearfix"></div>
       </div>
	   
	    <div><a class="toolButton" href="#">Tools</a><a class="saveButton">Save to my account</a><a class="sendButton">Send</a></div>
	  
	  
       
      </div>
	  
	  
	  
	  
	  <div aria-labelledby="guestbook-tab" id="guestbook" class="tab-pane fade" role="tabpanel">
	  
	  <div class="table-responsive">
      <table class="table table-bordered table-make">
        <thead>
          <tr>
            <th class="theads" colspan="4">Select obituaries</th>
          </tr>
        </thead>
        <tbody class="texts">
          <tr>
            <th>Language</th>
            <th>Styled</th>
            <th>Customized</th>
            <th>Newspapers</th>
          </tr>
        </tbody>
      </table>
    </div>
	
	<div class="row">
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.</a>
	</div>
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here.</a>
	</div>
	</div>
	
	
	<div class="row">
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.</a>
	</div>
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here.</a>
	</div>
	</div>
	
	<div class="row">
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.</a>
	</div>
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here.</a>
	</div>
	</div>
	
	<div class="row">
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.</a>
	</div>
	<div class="col-md-4">
	<a href="#" class="viewfile">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here.</a>
	</div>
	</div>
	
	<div class="text-center">
	<nav>
      <ul class="pagination pagination-lg">
        <li><a aria-label="Previous" href="#"><span aria-hidden="true">«</span></a></li>
        <li class="active"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a aria-label="Next" href="#"><span aria-hidden="true">»</span></a></li>
      </ul>
    </nav>
	</div>
	
       
      </div>
	 
	  
      
    </div>
</div>
<div class="clearfix"></div>
</div>



<script type="text/javascript">
document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("uploadFile").value = this.value;
};
</script>
</body>
</html>

