
<div class="header-bottom">
<div class="col-md-4">
<a class="logo-top" href="#">Cremation Planning <i class="fa fa-chevron-right"></i></a>
<a class="main-slide" href="#">Announce</a>
</div>

<div class="col-md-4">
<div class="floatr border-full">
<a class="alls first" href="page/faq">FAQ</a><a class="alls second" href="page/demo">Demo</a><a class="alls third" href="page/share">Share</a>
</div>
</div>

<div class="clearfix"></div>
</div>

<div class="section-band">
<div class="col-md-4 border-right text-center">
		<a href="<?php echo $this->url('uploadd');?>">
			<div id="back"></div>
			<img id='change' height="500px" width="100%" src="images/user.png" style="position:absolute; top:0; left:0px; z-index:0;" />
		</a>
		
		<p class="set-thumb">Deceased's Profile Name</p>
		<span class="set-band">Date: Oct 2,1869-Jan 30,1948</span>
				<div class='test' style="display:block;">
		<?php foreach($results_thmb as $result){
			$ext = $result['extension'];
			$doc_name = $result['file_name'];
			$path = '/addthis/upload/'.$doc_name;
			$src = $this->basepath().$path;
		?>
		
			<img class="inputs" src='<?php echo $src;?>'/>
		
		<?php }?></div>
		
	
	<div class="back_border">Add Audio, Video and Images</div>
		<select class="demoa form-controls">
		<option>Rest in Peace</option>
		  <option>R.I.P.</option>
		  <option>We miss you</option>
		  <option>Love you Forever</option>
		  <option>You won't be forgotten</option>
		  <option>You will always be in our hearts</option>
		  <option>Whereever you are, we love you</option>
		</select>
		
		<div class="set-img">
			<a href="<?php echo $this->url('third');?>">
				<img height='50px' width='50px' src="addthis/images/mala-2.png" />
				<img height='50px' width='50px' src="addthis/images/candle.jpg" />
				<img height='50px' width='50px' src="addthis/images/diya.jpg" />
			</a>
		</div>
			
				<p class="set-thumbs">Created by: Rajiv Bhatia</p>
				<span class="set-bands">Privacy Setting: Public</span>
		</div>
		<div class="col-md-8 border-left">
		  <div class="border-set" style="margin-top: 10px;>
       <div class="col-md-12">
       <div class="set-form">
      
	  <form>
	  <div class="form-group">
    <label for="exampleInputPassword1">Qualities: Best Singer, Most helpful</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Relationship: My Favourite Uncle</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Influence: Fan of your Music</label>
    <textarea placeholder="Message here..." rows="6" class="my-controls new-control"></textarea>
  </div>
  </form>

	  
      </div>
       </div>
       <div class="clearfix"></div>
       </div>
	   
	    <div><a class="toolButton" href="#">Tools</a><a class="saveButton">Save to my account</a><a class="sendButton">Send</a></div>
       </div>
		
		
<style>

	#back {
    background-image: url("addthis/images/mala-3.png");
	background-size:100% 100%;
	height:500px;
	position:relative;
	z-index:1;
}

</style>

 <script>
jQuery(document).ready(function ($) {            
             
      $('#radiofirst').click(function() {
        $('#MyaccountDiv').hide();
        $('#newDiv').show();        
      });
      $('#radiosecond').click(function() {
        $('#newDiv').hide();
        $('#MyaccountDiv').show();
      });

document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("uploadFile").value = this.value;
};

</script>
