  <script>
jQuery(document).ready(function ($) {            
             
      $('#radiofirst').click(function() {
        $('#MyaccountDiv').hide();
        $('#newDiv').show();        
      });
      $('#radiosecond').click(function() {
        $('#newDiv').hide();
        $('#MyaccountDiv').show();
      });         
             
      
            
            var options = {
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlayInterval: 4000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $SlideDuration: 500,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
                $UISearchMode: 0,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).

                $ThumbnailNavigatorOptions: {
                    $Class: $JssorThumbnailNavigator$,              //[Required] Class to create thumbnail navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always

                    $Loop: 2,                                       //[Optional] Enable loop(circular) of carousel or not, 0: stop, 1: loop, 2 rewind, default value is 1
                    $SpacingX: 3,                                   //[Optional] Horizontal space between each thumbnail in pixel, default value is 0
                    $SpacingY: 3,                                   //[Optional] Vertical space between each thumbnail in pixel, default value is 0
                    $DisplayPieces: 6,                              //[Optional] Number of pieces to display, default value is 1
                    $ParkingPosition: 204,                          //[Optional] The offset position to park thumbnail,

                    $ArrowNavigatorOptions: {
                        $Class: $JssorArrowNavigator$,              //[Requried] Class to create arrow navigator instance
                        $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                        $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                        $Steps: 6                                       //[Optional] Steps to go for each navigation request, default value is 1
                    }
                }
            };

            var jssor_slider1 = new $JssorSlider$("slider1_container", options);

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                if (parentWidth)
                    jssor_slider1.$ScaleWidth(Math.min(parentWidth, 447));
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
   
document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("uploadFile").value = this.value;
};

</script>




<div class="header-bottom">


<div class="section-band">
<div class="col-md-4 border-right text-center">
<!--<a href="#"><img class="img-responsive" src="images/user.png" /></a>-->




    <div id="slider1_container" style="position: relative; width: 447px;
        height: 370px; overflow: hidden;">

        <!-- Loading Screen -->
        <div u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
                background-color: #000; top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
            <div style="position: absolute; display: block; background: url(../img/loading.gif) no-repeat center center;
                top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
        </div>

        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 447px; height: 279px;
            overflow: hidden;">
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/01.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-01.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/02.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-02.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/03.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-03.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/04.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-04.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/05.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-05.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/06.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-06.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/07.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-07.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/08.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-08.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/09.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-09.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/10.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-10.jpg');?>" />
            </div>

            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/11.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-11.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/12.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-12.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/13.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-13.jpg');?>" />
            </div>
            <div>
                <img u="image" src="<?php echo $this->basePath('/images/travel/14.jpg');?>" />
                <img u="thumb" src="<?php echo $this->basePath('/images/travel/thumb-14.jpg');?>" />
            </div>
        </div>
        
        
        <!-- Thumbnail Navigator Skin Begin -->
        
        <p  style="font-family: openFont2;
font-size: 17px;
padding-top: 280px;
margin-bottom: 2px !important;
color: #FF7F50; ">Created by: Rajiv Bhatia</p>
<span class="set-bands">Privacy Setting: Public</span>
        
        
        <div u="thumbnavigator" class="jssort07" style="position: absolute; width: 447px; height: 100px; left: 0px; bottom: 0px; overflow: hidden; ">
            <div style=" background-color: #000; filter:alpha(opacity=30); opacity:.3; width: 100%; "></div>
            <!-- Thumbnail Item Skin Begin -->
          
            <div u="slides" style="cursor: move;">
                <div u="prototype" class="p" style="POSITION: absolute; WIDTH: 50px; HEIGHT: 40px; TOP: 0; LEFT: 0;">
                    <div u="thumbnailtemplate" class="i" style="position:absolute;"></div>
                    <div class="o">
                    </div>
                </div>
            </div>
            <!-- Thumbnail Item Skin End -->
            <!-- Arrow Navigator Skin Begin -->
            
            <!-- Arrow Left -->
            <span u="arrowleft" class="jssora11l" style="width: 37px; height: 37px; top: 123px; left: 8px;">
            </span>
            <!-- Arrow Right -->
            <span u="arrowright" class="jssora11r" style="width: 37px; height: 37px; top: 123px; right: 8px">
            </span>
            <!-- Arrow Navigator Skin End -->
        </div>
        
        <!-- Trigger -->
    </div>




<p class="set-thumb">Deceased's Profile Name</p>
<span class="set-band">Date: Oct 2,1869-Jan 30,1948</span>


<div class="back_border">
	<form method="post" enctype="multipart/form-data" action="<?php echo $this->url('upload');?>">
		<input type="file" name="file" class='btn btn-success'/>
		<input type='submit' class='btn btn-success' value = 'Add Audio, Video and Images'> 
		
	</form>

</div>
<select class="demoa form-controls">
  <option>Rest in peace</option>
  <option>Rest in peace</option>
  <option>Rest in peace</option>
  <option>Rest in peace</option>
  <option>Rest in peace</option>
</select>
<div class="set-img"><img src="<?php echo $this->basePath('/images/adminimage.jpg');?>" /><img src="<?php echo $this->basePath('/images/adminimage.jpg');?>" /><img src="<?php echo $this->basePath('/images/adminimage.jpg');?>" /></div>

</div>


<div class="col-md-8 border-left">
<h3>All Images/Audio/Video List</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <th>SNo.</th>
        <th>Name</th>
        <th>Action</th>
        <th>Download</th>
    </thead>
	<?php $count = count($results);
		$no = 1;
		if($count== '' || $count== NULL){?>
			<tbody><?php echo $this->translate('No Record Found');?></tbody>
			
		<?php }
		 foreach($results as $result){?>
			<tr>
				<th><?php echo $no;?></th>
				<th><?php echo $result['name'];?></th>
				<th>
					<a href="<?php echo $this->url('play').'?id='.$result['id'];?>" >
						<?php echo $this->translate('Play/Show');?>
					</a>
				</th>
				<th>				
					<a href="<?php echo $this->url('download').'?id='.$result['id'];?>">
						<img src="<?php echo $this->basepath().'/addthis/images/download.ico';?>" height='50px' alt='Download'>
					</a>
				</th>
			</tr>
			
	<?php $no++; }?>
	
</table>
</div>


<div class="clearfix"></div>
</div>


</div>




