<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/jquery.dataTables.min.css';?>"/>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
 <script src="<?php echo $this->basePath() . '/assets/js/jquery.dataTables.min.js';?>"></script>
<script>

jQuery(document).ready(function ($) {            
           
      $('#radiofirst').click(function() {
        $('#MyaccountDiv').hide();
        $('#newDiv').show();        
      });
      $('#radiosecond').click(function() {
        $('#newDiv').hide();
        $('#MyaccountDiv').show();
      });
	  
	 

	$('.test img').click(function() {
    var img = $(this).attr('src');
	$('#change').attr("src",img);
	});
	
	
	$('.value').click(function(){
		var value = $(this).find("a").attr('data');
		// alert(value);
		$('#set').attr('value',value);
	});
	
	/* function Demo(anchor) {
        var value = anchor.getAttribute('value')
        alert(value);
    } */
	$("#langTable").dataTable({
		"bFilter": false,
		"ordering": false,
"bRetrieve": true	
	});

});

function getlanguagetext() {
	var ltext=$("#languageSelect").val();
	var data='ltext='+ltext;
	$.ajax({
		url:"<?php echo $this->basePath('/languagetext');?>",
		data:	data,
		type:"post",
		async:false,
		success:function (res) {
	
			$("#ltext").empty();
			var resul=$.parseJSON(res);
				//alert(resul.toSource());
			var opt="";
			opt +="<table id='langTable' width='100%'>";
			opt +="<thead>";
			opt +="<tr><th></th><th></th><th></th></tr>";					
			opt +="</thead>";		
			opt +="<tbody>";
			$.each(resul, function (k,v) {
			
				var oid=v['id'];
				opt +="<tr>";
				opt +="<td width='33%' style='border-bottom:1px solid #ccc'>";
				opt +="<div class='value'>";
				opt +="<input type='radio' name='lang[description-"+oid+"]' id='small_description-"+oid+"' value='small_description-"+oid+"'/>";
				opt +="<a class='viewfile color1'  style='height:88px' data='Lorem ipsum dolor sit amet' href='javascript:void(0)'>"+v['small_description']+"</a>";
				opt +="</div>";
				opt +="</td>";
				opt +="<td width='33%' style='border-bottom:1px solid #ccc'>";	
				opt +="<div class='value'>";
				opt +="<input type='radio' name='lang[description-"+oid+"]' id='large_description-"+oid+"'  value='large_description-"+oid+"'/>";
				opt +="<a class='viewfile color1'  style='height:88px' data='Lorem ipsum dolor sit amet' href='javascript:void(0)'>"+v['large_description']+"</a>";
				opt +="</div>";
				opt +="</td>";
				opt +="<td width='33%' style='border-bottom:1px solid #ccc'>";
				opt +="<div class='value'>";
				opt +="<input type='radio' name='lang[description-"+oid+"]' id='extralarge_description-"+oid+"' value='extralarge_description-"+oid+"' />";
				opt +="<a class='viewfile color1'  style='height:88px' data='Lorem ipsum dolor sit amet' href='javascript:void(0)'>"+v['extralarge_description']+"</a>";
				opt +="</div>";
				opt +="</td>";
			});
			opt +="</tbody>";
		opt +="</table>";	
			$("#ltext").append(opt);
		},

error:function(res){
//alert(res.toSource());
res=res.responseText;
//alert(res);
$("#ltext").empty();
			var resul=$.parseJSON(res);
				//alert(resul.toSource());
			var opt="";
			opt +="<table id='langTable' width='100%'>";
			opt +="<thead>";
			opt +="<tr><th></th><th></th><th></th></tr>";					
			opt +="</thead>";		
			opt +="<tbody>";
			$.each(resul, function (k,v) {
			
				var oid=v['id'];
				opt +="<tr>";
				opt +="<td width='33%' style='border-bottom:1px solid #ccc'>";
				opt +="<div class='value'>";
				opt +="<input type='radio' name='lang[description-"+oid+"]' id='small_description-"+oid+"' value='small_description-"+oid+"'/>";
				opt +="<a class='viewfile color1'  style='height:88px' data='Lorem ipsum dolor sit amet' href='javascript:void(0)'>"+v['small_description']+"</a>";
				opt +="</div>";
				opt +="</td>";
				opt +="<td width='33%' style='border-bottom:1px solid #ccc'>";	
				opt +="<div class='value'>";
				opt +="<input type='radio' name='lang[description-"+oid+"]' id='large_description-"+oid+"'  value='large_description-"+oid+"'/>";
				opt +="<a class='viewfile color1'  style='height:88px' data='Lorem ipsum dolor sit amet' href='javascript:void(0)'>"+v['large_description']+"</a>";
				opt +="</div>";
				opt +="</td>";
				opt +="<td width='33%' style='border-bottom:1px solid #ccc'>";
				opt +="<div class='value'>";
				opt +="<input type='radio' name='lang[description-"+oid+"]' id='extralarge_description-"+oid+"' value='extralarge_description-"+oid+"' />";
				opt +="<a class='viewfile color1'  style='height:88px' data='Lorem ipsum dolor sit amet' href='javascript:void(0)'>"+v['extralarge_description']+"</a>";
				opt +="</div>";
				opt +="</td>";
			});
			opt +="</tbody>";
		opt +="</table>";	
			$("#ltext").append(opt);
}
	});

	$("#langTable").dataTable({
		"bFilter": false,
		"ordering": false,
"bRetrieve": true	
	});
}
    

 
/* 
function addmeobi(text)
{
  // var text = get;
	alert(text);

};*/
</script>

<style>
#back {
   /* background-image: url("addthis/images/mala-2.png");*/
	background-size:100% 100%;
	height:500px;
	position:relative;
	z-index:1;
}
.pad li a{
	padding: 10px 110px 10px 55px !important;
}

.set-nav{
	margin-top:0px;
}

.theadse {
    background-color: #ff7f50;
    border-bottom: 0 none !important;
    color: #fff;
    font-family: openFont1;
    font-size: 21px;
    padding: 7px 15px;
	width:100%;
	margin-top:12px;
	margin-bottom:12px;
}
.value{
border: 1px solid #ccc;
    border-radius: 8px;
}
.value:hover{
border: 1px solid #ccc;
    border-radius: 8px;
	box-shadow:0 0 2px #777;
}
.new-set{
	
	right: 24px;
}

.right_side{  margin-top:-6px; border:none; background:none !important; text-decoration:underline;}
.right_side:hover{ margin-top:-6px; border:none; text-decoration:underline !important; color:#777 !important;}

.btn.btn-default.click-butt{ margin-top:-16px !important;}
input[type="radio"], input[type="checkbox"] {
    line-height: normal;
    margin: 11px 0px 0 8px !important;
	vertical-align:top;
}
.viewfile.color1{ 
    color: #777;
    display: inline-block;
    font-family: openFont1;
    font-size: 14px;
    height: 220px;
    line-height: 25px;
    margin-bottom: 30px;
    padding: 4px 4px!important;
    width: 92%;
}



@media (max-width:530px) {
	.theadse { font-size:16px; }
	.btn.btn-default.click-butt{ margin-top:0px !important; width:330px;}
	.select-obituary .nav.nav-tabs.navs.set-nav.new_style li { width:48%;}
	.select-obituary .nav.nav-tabs.navs.set-nav.new_style li a {width:100%;}
	}
	
</style>





<div class="header-bottom">
	<div class="col-md-4">
		<a class="logo-top" href="#">Cremation Planning <i class="fa fa-chevron-right"></i></a>
		<a class="main-slide" href="#">Announce</a>
	</div>
	
   <div class="col-md-4">
		<div class="button-radio">
			<!--<input type="radio" checked="checked" name="radiog_lite" id="radiofirst" class="css-checkbox"> <label for="radiofirst" class="css-label1 radGroup1">Create New</label> <input type="radio" name="radiog_lite" id="radiosecond" class="css-checkbox"> <label for="radiosecond" class="css-label1 radGroup1">My Account</label>-->
		</div>
	</div>
    
	<div class="col-md-4">
		<div class="floatr border-full">
			<a class="alls first" href="#">FAQ</a><a class="alls second" href="#">Demo</a><a class="alls third" href="#">Share</a>
		</div>
	</div>

	<div class="clearfix"></div>
</div>

<div class="section-band">
	<div class="col-md-4 border-right text-center">
    <?php 

				if(sizeof($result_thmb2)>0){			
			foreach($result_thmb2 as $result2){
				
				$doc_name2 = $result2['image_url'];
				
				$path2 = '/../module/Application/assets/images/'.$deathuserid.'/'.$doc_name2;
			
				$src2 = $this->basepath().$path2;
			?>
			<a href="<?php echo $this->url('uploadd');?>">
			<div id="back"></div>
			<img id='change' class="user-img" height='500px' width='100%' src='<?php echo $src2;?>' style="position:absolute; top:0;left:0px; z-index:0;" />
		
			<p class="set-thumb" style="text-decoration:none; width:100%;
    margin-top: -75px;
    position: absolute;"><?php if($draft_data->first_name!="" || $draft_data->middle_name!="" || $draft_data->last_name!="") { echo $draft_data->first_name.' '.$draft_data->middle_name.' '.$draft_data->last_name; } else { echo "Deceased's Profile Name"; } ?><span class="set-band" ><?php if($draft_data->date_of_birth!="") { echo 'Date: '.date('M d, Y',strtotime($draft_data->date_of_birth)).'-'.date('M d, Y',strtotime($draft_data->date_of_death)); } else { ?>Date: Oct 2,1869-Jan 30,1948<?php } ?></span></p>    
			<!--<img class="img-responsive" src="images/user.png" />-->
		</a>
			<?php	
break;				
			}
			}else{
?>
<a href="<?php echo $this->url('uploadd');?>">
			<div id="back">
            </div>
           
				<img id='change' class="user-img" height='500px' width='100%' src="images/user.png" style="position:absolute; top:0;left:0px; z-index:0;"/>
         <p class="set-thumb" style="text-decoration:none; width:100%;
    margin-top: -75px;
    position: absolute;"><?php if($draft_data->first_name!="" || $draft_data->middle_name!="" || $draft_data->last_name!="") { echo $draft_data->first_name.' '.$draft_data->middle_name.' '.$draft_data->last_name; } else { echo "Deceased's Profile Name"; } ?><span class="set-band" ><?php if($draft_data->date_of_birth!="") { echo 'Date: '.date('M d, Y',strtotime($draft_data->date_of_birth)).'-'.date('M d, Y',strtotime($draft_data->date_of_death)); } else { ?>Date: Oct 2,1869-Jan 30,1948<?php } ?></span></p>        
		</a>
<?php			
			}?>
   <div class="col-md-12 col-sm-12 the-controlling-images">
    <div class='test' style="display: block; margin:10px 0;">

<?php

$count = count ( $result_thmb );
if ($count > 0) {
	foreach ( $result_thmb as $result ) {
		$ext = $result ['extension'];
		$doc_name = $result ['image_url'];
		$path = '/../module/Application/assets/images/'.$deathuserid.'/'.$doc_name;
		$src = $this->basepath () . $path;
		?>
<img class="inputs" src='<?php echo $src;?>' />
<?php }}?>
<?php

$path = '/addthis/images/imagenouser.png';
for($i = $count; $i < 8; $i ++) {
	?>
<img class='inputs' src='<?php echo $this->basepath(). '/addthis/images/imagenouser.png';?>' />
<?php } ?>


</div>
   </div>
   <!-- <div class="back_border">Add Audio, Video and Images</div>-->
    <select class="demoa  form-controls">
      <option>Rest in Peace</option>
      <option>R.I.P.</option>
      <option>We miss you</option>
      <option>Love you Forever</option>
      <option>You won't be forgotten</option>
      <option>You will always be in our hearts</option>
      <option>Whereever you are, we love you</option>
    </select>
    
   <div class="offertings-block">
    <div class="set-img left-img1">
      <a href="<?php echo $this->url('third');?>">
       <img class="img-responsive"  src="addthis/images/mala-2.png" /> 
      </a>
    </div>
    
    <div class="greetings">
    	<p> Offerings </p>
                    <div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/candlee.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/diya1.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/thali.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/wreath.jpg";?>" class="inputs" title='count:1'>
                    </div>
                    <div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/namste-offering.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/ome-offering.jpg";?>" class="inputs" title='count:1'>
						  <img src="<?php echo $this->basepath(). "/addthis/images/dove.png";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/dayofdeath.png";?>" class="inputs" title='count:1'>
                    
                  </div>
                    <div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/candles.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/Growing-Tulsi-2.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/ashoka-chakra.jpg";?>"  class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/havan.jpg";?>" class="inputs" title='count:1'>
                    </div>               </div>
   </div>
    <p class="set-thumbs"  style="cursor:pointer;">Created by: Rajeev Bhatia</p>
    <?php
   if($deathuserid){
	?>
	<span class="set-bands" onclick="privacyDivFn()" style="cursor:pointer">Privacy Settings</span>
	<?php	   
   }else {
?>
<span class="set-bands">Privacy Settings</span>
<?php   
   }
	
    ?>
    
  </div>

<div role="tabpanel" class="tab-pane fade active in">

	<div class="col-md-8 border-left">  
	<h4 class="theadse">Select obituaries <span> <a class="right_side btn btn-default" href="javascript:history.back(1);">Back</a>  </span> </h4>
    <div class="select-obituary">
		<ul role="tablist" class="nav nav-tabs navs  set-nav new_style" id="myTab">
			<li class="active" role="presentation"><a aria-expanded="true" aria-controls="language" class="" data-toggle="tab" role="tab" id="language-tab" href="#language">Language</a></li>
			<!--<li role="presentation" class=""><a  class="" aria-controls="styled" data-toggle="tab" id="styled-tab" role="tab" href="#styled" aria-expanded="false">Styled</a></li>-->
			
			<li role="presentation" class=""><a class="" aria-controls="newspaper" data-toggle="tab" id="newspaper-tab" role="tab" href="#newspaper" aria-expanded="false">Newspapers </a></li>
			 <!--<li role="presentation" class=""><a class=" btn btn-default" href="<?php echo $this->url('home') ?>">Back</a></li>-->
            
			
		</ul>
   </div>
    <div class="clearfix"></div>  
<?php $link= $this->url('style',array(), array('force_canonical' => true)).'?step='.$_GET['step'];?>
	<form method='post' action="<?php echo $link;?>">
		<input type='hidden' name='value' id='set' value=''>
	<div class="tab-content" id="myTabContent">
		<div aria-labelledby="language-tab" id="language" class="tab-pane fade active in" role="tabpanel">
        <div class="clear"> </div>
			<div class="border-set">
			<div class="the-tax-menu">
			<select name="languageSelect" id="languageSelect" multiple="multliple" style="font-size: 17px;width: 330px; height:130px; ">
			<?php 
				foreach($languages as $lang){
			?>
				<option value="<?php echo $lang['value'];?>"><?php echo $lang['value'];?></option>
			<?php 
				} 
			?>	
				</select>	
				 <button class="btn btn-default click-butt" type='button' onclick="getlanguagetext()" name = 'sub'>Select</button> 		
			</div>
				<div class="col-md-12">
					<div class="set-form">
						<div class="row" id="ltext">
					<table id="langTable" width="100%">
					<thead>
					<tr><th></th><th></th><th></th></tr>					
					</thead>		
					<tbody>
			<?php 
				foreach($languagesText as $langText){
			?>
			<tr>
			<td width="33%" style="border-bottom:1px solid #ccc">
				<div class="value">
			<input type='radio' name='lang[description-<?php echo $langText['id'];?>]' id='small_description-<?php echo $langText['id'];?>' value='small_description-<?php echo $langText['id'];?>'/>
				<a class="viewfile color1"  style="height:88px" data="Lorem ipsum dolor sit amet" href="javascript:void(0)"><?php echo $langText['small_description'];?> </a>
</div>				
			</td>			
			<td  width="33%" style="border-bottom:1px solid #ccc">
				<div class="value">
<input type='radio' name='lang[description-<?php echo $langText['id'];?>]' id='large_description-<?php echo $langText['id'];?>' value='large_description-<?php echo $langText['id'];?>'/>
				<a class="viewfile color1"  style="height:88px" data="Lorem ipsum dolor sit amet" href="javascript:void(0)"><?php echo $langText['large_description'];?> </a>
</div>			
			</td>			
			<td  width="33%" style="border-bottom:1px solid #ccc">
				<div class="value">
<input type='radio' name='lang[description-<?php echo $langText['id'];?>]' id='extralarge_description-<?php echo $langText['id'];?>' value='extralarge_description-<?php echo $langText['id'];?>'/>
				<a class="viewfile color1"  style="height:88px" data="Lorem ipsum dolor sit amet" href="javascript:void(0)"><?php echo $langText['extralarge_description'];?> </a>
</div>				
			</td>			
			</tr>
			<?php 
				} 
			?>	
			</tbody>		
	</table>

	</div>
	</div>
	</div>
    <div class="clearfix"></div>
	</div>
	</div>
		<div aria-labelledby="styled-tab" id="styled" class="tab-pane fade" role="tabpanel">
			<div class="border-set">
				<div class="col-md-12">
					<div class="set-form">
						<div class="row">
							<div class="col-md-4 value">
							<a class="viewfile color1 value" style="height:88px" href="javascript:addmeobi();" data='Lorem ipsum dolor sit amet'>Lorem ipsum dolor sit amet </a>
			<!--	<a class="viewfile color1" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="Lorem ipsum dolor sit amet" >Lorem ipsum dolor sit amet </a>	-->			
							</div>
							<div class="col-md-4 value">
								<a class="viewfile color2" style="height:88px" href="javascript:addmeobi();" data="But I must explain to you how all this mistaken idea.">But I must explain to you how all this mistaken idea.</a>
			
			<!--<a class="viewfile color2" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="But I must explain to you how all this mistaken idea." >But I must explain to you how all this mistaken idea.</a>-->
							</div>
							<div class="col-md-4 value">
								<a class="viewfile color3" data="At vero eos et accusamus et iusto odio dignissimos ducimus." style="height:88px" href="javascript:addmeobi();">At vero eos et accusamus et iusto odio dignissimos ducimus.</a>
	<!--<a class="viewfile color3" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="At vero eos et accusamus et iusto odio dignissimos ducimus." >At vero eos et accusamus et iusto odio dignissimos ducimus.</a>		-->			
		</div>
						</div>
						<div class="row">
							<div class="col-md-4 value">
								<a class="viewfile color1" data="Lorem ipsum dolor sit amet"style="height:88px" href="javascript:addmeobi();">Lorem ipsum dolor sit amet </a>
		<!--<a class="viewfile color1" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="Lorem ipsum dolor sit amet." >Lorem ipsum dolor sit amet.</a>	-->				
							</div>
							<div class="col-md-4 value">
							<a class="viewfile color2" style="height:88px" data="But I must explain to you how all this mistaken idea." href="javascript:addmeobi();">But I must explain to you how all this mistaken idea.</a>
					<!--<a class="viewfile color2" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="But I must explain to you how all this mistaken idea." >But I must explain to you how all this mistaken idea.</a>		-->	
							</div>
							<div class="col-md-4 value">
								<a class="viewfile color3" data='At vero eos et accusamus et iusto odio dignissimos ducimus.' style="height:88px" href="javascript:addmeobi();">At vero eos et accusamus et iusto odio dignissimos ducimus.</a>
				<!--<a class="viewfile color3" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="At vero eos et accusamus et iusto odio dignissimos ducimus" >At vero eos et accusamus et iusto odio dignissimos ducimus.</a>			-->	
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div aria-labelledby="newspaper-tab" id="newspaper" class="tab-pane fade" role="tabpanel">
			<div class="border-set">
				<div class="col-md-12">
					<div class="set-form">
						<div class="row">
							<div class="col-md-4 value">
								<a class="viewfile color1" data="Lorem ipsum dolor sit amet" style="height:88px" href="javascript:addmeobi();">Lorem ipsum dolor sit amet</a>
		<!--	<a class="viewfile color1" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="Lorem ipsum dolor sit amet" >Lorem ipsum dolor sit amet.</a>	-->				
							</div>
							<div class="col-md-4 value">
								<a class="viewfile color2" data="But I must explain to you how all this mistaken idea." style="height:88px" href="javascript:addmeobi();">But I must explain to you how all this mistaken idea. </a>
	<!--	<a class="viewfile color2" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="But I must explain to you how all this mistaken idea" >But I must explain to you how all this mistaken idea.</a>	-->					
							</div>
							<div class="col-md-4 value">
							<a class="viewfile color3" data="At vero eos et accusamus et iusto odio dignissimos ducimus." style="height:88px" href="javascript:addmeobi();">At vero eos et accusamus et iusto odio dignissimos ducimus. </a>
			<!--	<a class="viewfile color3" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="At vero eos et accusamus et iusto odio dignissimos ducimus" >At vero eos et accusamus et iusto odio dignissimos ducimus.</a>	-->			
							</div>
						</div>
						<div class="row">
							<div class="col-md-4 value">
								<a class="viewfile color1" data="Lorem ipsum dolor sit amet" style="height:88px" href="javascript:addmeobi();">Lorem ipsum dolor sit amet</a>
		<!--	<a class="viewfile color1" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="Lorem ipsum dolor sit amet" >Lorem ipsum dolor sit amet.</a>	-->			
							</div>
							<div class="col-md-4 value">
								<a class="viewfile color2" data="But I must explain to you how all this mistaken idea." style="height:88px" href="javascript:addmeobi();">But I must explain to you how all this mistaken idea. </a>
		<!--	<a class="viewfile color2" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="But I must explain to you how all this mistaken idea" >But I must explain to you how all this mistaken idea.</a>		-->	
							</div>
							<div class="col-md-4 value">
								<a class="viewfile color3" data="At vero eos et accusamus et iusto odio dignissimos ducimus." style="height:88px" href="javascript:addmeobi();">At vero eos et accusamus et iusto odio dignissimos ducimus. </a>
		<!--	<a class="viewfile color3" onclick="Demo(this);"    href="javascript:void(0)" style="height:88px" value="At vero eos et accusamus et iusto odio dignissimos ducimus" >At vero eos et accusamus et iusto odio dignissimos ducimus.</a>	-->			
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	
	
	<div class="new-set">
		<button class="saveButton" type='submit' name = 'sub'>Save to my account</button>
	</div>
	</form>
</div>
</div>
 <div class="clearfix"></div>

</div>

	
	
	
	
	 <!-- <div class="table-responsive">
		<table class="table table-bordered table-make">
			<thead>
				<tr>
					<th colspan="4" class="theads">Select obituaries</th>
				</tr>
			</thead>
			<tbody class="texts">
			  <tr>
				<th>Language</th>
				<th>Styled</th>
				<th>Customized</th>
				<th>Newspapers</th>
			  </tr>
			</tbody>
		</table>
      </div>-->
<!--	
<div class="row">
	<div class="col-md-4">
		<a class="viewfile color1" href="#">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
		<a class="viewfile color2" href="#">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
		<a class="viewfile color3" href="#">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
</div>
	
<div class="row">
	<div class="col-md-4">
		<a class="viewfile color1" href="#">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
		<a class="viewfile color2" href="#">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
		<a class="viewfile color3" href="#">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>

</div>
<div class="row">
	<div class="col-md-4">
		<a class="viewfile color1" href="#">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
		<a class="viewfile color2" href="#">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>
	<div class="col-md-4">
		<a class="viewfile color3" href="#">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. </a>
	</div>

</div>

	<div class="text-center">
		<nav>
		  <ul class="pagination pagination-lg">
			<li><a href="#" aria-label="Previous"><span aria-hidden="true">\AB</span></a></li>
			<li class="active"><a href="#">1</a></li>
			<li><a href="#">2</a></li>
			<li><a href="#">3</a></li>
			<li><a href="#">4</a></li>
			<li><a href="#">5</a></li>
			<li><a href="#" aria-label="Next"><span aria-hidden="true">\BB</span></a></li>
		  </ul>
		</nav>
	</div>
	
</div>
	
</div>
</div>

-->
    
     
