<script>
jQuery(document).ready(function ($) {            
             
      $('#radiofirst').click(function() {
        $('#MyaccountDiv').hide();
        $('#newDiv').show();        
      });
      $('#radiosecond').click(function() {
        $('#newDiv').hide();
        $('#MyaccountDiv').show();
      });
	  
	 

	$('.test img').click(function() {
    var img = $(this).attr('src');
	$('#change').attr("src",img);
	});
	
});

document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("uploadFile").value = this.value;
};

</script>

<style>
	#back {
    background-image: url("addthis/images/mala-3.png");
	background-size:100% 100%;
	height:500px;
	position:relative;
	z-index:1;
}

</style>




<div class="header-bottom">
<div class="col-md-4">
<a class="logo-top" href="#">Cremation Planning <i class="fa fa-chevron-right"></i></a>
<a class="main-slide" href="#">Announce</a>
</div>

<div class="col-md-4">
	<!--<div class="button-radio">
	<input type="radio" class="css-checkbox" id="radiofirst" name="radiog_lite" checked="checked" >
	<label class="css-label1 radGroup1" for="radiofirst">Create New</label>

	<input type="radio" class="css-checkbox" id="radiosecond" name="radiog_lite">
	<label class="css-label1 radGroup1" for="radiosecond">My Account</label>
	</div>-->
</div>

<div class="col-md-4">
<div class="floatr border-full">
<a class="alls first" href="page/faq">FAQ</a><a class="alls second" href="page/demo">Demo</a><a class="alls third" href="page/share">Share</a>
</div>
</div>

<div class="clearfix"></div>
</div>

<div class="section-band">
	<div class="col-md-4 border-right text-center">
		<a href="#">
			<div id="back"></div>
			<img id='change' height="500px" width="100%" src="images/user.png" style="position:absolute; top:0; left:0px; z-index:0;" />
<p class="set-thumb" style="text-decoration:none;left: 170px;
    margin-top: -75px;
    position: absolute;z-index: 999999">Deceased's Profile Name
		<span class="set-band">Date: Oct 2,1869-Jan 30,1948</span></p>	
		</a>
		
		
				<div class='test' style="display:block;">
		<?php foreach($results_thmb as $result){
			$ext = $result['extension'];
			$doc_name = $result['file_name'];
			$path = '/addthis/upload/'.$doc_name;
			$src = $this->basepath().$path;
		?>
		
			<img class="inputs" src='<?php echo $src;?>'/>
		
		<?php }?></div>
		
	
<!--	<div class="back_border">Add Audio, Video and Images</div>-->
		<select class="demoa form-controls">
		<option>Rest in Peace</option>
		  <option>R.I.P.</option>
		  <option>We miss you</option>
		  <option>Love you Forever</option>
		  <option>You won't be forgotten</option>
		  <option>You will always be in our hearts</option>
		  <option>Whereever you are, we love you</option>
		</select>
		
		<div class="set-img">
			<a href="<?php echo $this->url('third');?>">
				<img height='50px' width='50px' src="addthis/images/mala-2.png" />
				<img height='50px' width='50px' src="addthis/images/candle.jpg" />
				<img height='50px' width='50px' src="addthis/images/diya.jpg" />
			</a>
		</div>
			
				<p class="set-thumbs">Created by: Rajiv Bhatia</p>
				<span class="set-bands">Privacy Setting: Public</span>
		</div>


<div class="col-md-8 border-left"  style="margin-top:5px">

	<div class="border-set">
       <div class="col-md-12">
		<div class="set-form">
      
			<h4 class="new-text">Please Select a Garland for the Cover Image</h4>
			<a class='right_side btn btn-default' href='javascript:history.back(1);'>Back</a>
			<hr style="border-top:1px solid #777" > 
	
			<div class="row">
				
			<?php foreach($results as $result){
				$ext = $result['extension'];
				$doc_name = $result['file_name'];
				$path = '/addthis/upload/'.$doc_name;
			?>
				<div class="col-md-3">
					<div class="small_img"></div>
						<img class="" src="<?php echo $this->basepath().$path?>" width="190" height="180" style="position:absolute; top:0; z-index:0;left:30px;" />
						
				</div>
			<?php }?>	
				
			</div>
			
			
		</div>
      </div>
    <div class="clearfix"></div>
    </div>

</div>


    
     