<script>
jQuery(document).ready(function ($) {            
             
      $('#radiofirst').click(function() {
        $('#MyaccountDiv').hide();
        $('#newDiv').show();        
      });
      $('#radiosecond').click(function() {
        $('#newDiv').hide();
        $('#MyaccountDiv').show();
      });
            
            var options = {
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlayInterval: 4000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $SlideDuration: 500,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
                $UISearchMode: 0,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).

                $ThumbnailNavigatorOptions: {
                    $Class: $JssorThumbnailNavigator$,              //[Required] Class to create thumbnail navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always

                    $Loop: 2,                                       //[Optional] Enable loop(circular) of carousel or not, 0: stop, 1: loop, 2 rewind, default value is 1
                    $SpacingX: 3,                                   //[Optional] Horizontal space between each thumbnail in pixel, default value is 0
                    $SpacingY: 3,                                   //[Optional] Vertical space between each thumbnail in pixel, default value is 0
                    $DisplayPieces: 6,                              //[Optional] Number of pieces to display, default value is 1
                    $ParkingPosition: 204,                          //[Optional] The offset position to park thumbnail,

                    $ArrowNavigatorOptions: {
                        $Class: $JssorArrowNavigator$,              //[Requried] Class to create arrow navigator instance
                        $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                        $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                        $Steps: 6                                       //[Optional] Steps to go for each navigation request, default value is 1
                    }
                }
            };

            var jssor_slider1 = new $JssorSlider$("slider1_container", options);

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                if (parentWidth)
                    jssor_slider1.$ScaleWidth(Math.min(parentWidth, 447));
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
   
document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("uploadFile").value = this.value;
};

</script>
 
<div class="header-bottom">
<div class="col-md-4">
<a class="logo-top" href="#">Cremation Planning <i class="fa fa-chevron-right"></i></a>
<a class="main-slide" href="#">Announce</a>
</div>

<div class="col-md-4">
<div class="button-radio">
<input type="radio" class="css-checkbox" id="radiofirst" name="radiog_lite" checked="checked" >
<label class="css-label1 radGroup1" for="radiofirst">Create New</label>

<input type="radio" class="css-checkbox" id="radiosecond" name="radiog_lite">
<label class="css-label1 radGroup1" for="radiosecond">Created Profiles</label>
</div>
</div>

<div class="col-md-4">
<div class="floatr border-full">
<a class="alls first" href="page/faq">FAQ</a><a class="alls second" href="page/demo">Demo</a><a class="alls third" href="page/share">Share</a>
</div>   
</div>

<div class="clearfix"></div>
</div>

<div class="section-band section-color">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>
	function videoPlay(videoNum)
    {	
document.getElementById("video-box").setAttribute("src",videoNum);
document.getElementById("video-box").load();
document.getElementById("video-box").play();
    }
	function videoclose()
    {	
document.getElementById("video-box").pause();
    }
	
	
$(document).ready(function(){
	$('.test img').click(function() {
    var img = $(this).attr('src');
	$('#change').attr("src",img);
	});
});
</script>
<style type="text/css"> 
	.button { width: 150px; padding: 10px; background-color: #FF8C00; box-shadow: -8px 8px 10px 3px rgba(0,0,0,0.2); font-weight:bold; text-decoration:none; }
	#cover{ position:fixed; top:0; left:0; background:rgba(0,0,0,0.6); z-index:5; width:100%; height:100%; display:none; } 
	#loginScreen { height:500px; width:100%; margin:0 auto; position:relative; z-index:10; display:none; background-color: #428bca; border:5px solid #cccccc; border-radius:10px;margin-left:-20%; } 
	#loginScreen:target, #loginScreen:target + #cover{ display:block; opacity:2; } 
	.cancel { display:block; position:absolute; top:3px; right:2px; background:rgb(245,245,245); color:black; height:25px; width:25px; font-size:20px; text-decoration:none; text-align:center; font-weight:bold; } 
	#video-box{height:400px;width:100%;margin-top:-90px;background-color:#428bca;}
	</style>

  <div class="col-md-4 col-sm-12 border-right text-center">
    <?php 
//echo 
				if(sizeof($result_thmb2)>0){			
			foreach($result_thmb2 as $result2){
				
				$doc_name2 = $result2['image_url'];
				
				$path2 = '/../module/Application/assets/images/'.$deathuserid.'/'.$doc_name2;
			$info1=pathinfo($path2);
	    $ext1=$info1['extension'];	
				$src2 = $this->basepath().$path2;
			?>
			<a href="<?php echo $this->url('uploadd');?>">
			<div id="back"></div>
				
			<!--img src='<?php echo $src2;?>' id='change' class="user-img" height='500px' width='100%'  style="position:absolute; top:0;left:0px; z-index:0;" /> -->
			<!-- video play at palc of image	 -->
				<?php
				if($ext1=='mp4' || $ext1=='webm' || $ext1=='ogg')
						{
						?>	
				
				<video id='change' class="user-img" style="width:100%;height:500px;position:absolute; top:0;left:0px; z-index:0;" controls>
  <source src="<?php echo $src2;?>" type="video/mp4">
</video>
									
							
						<?php } 
							if($ext1=='mp3' || $ext1=='mpeg')
							{
						?>
							
								
									<audio id='change' class="user-img" style="width:100%;height:500px;position:absolute; top:0;left:0px; z-index:0;" controls>
										
  <source  src="<?php echo $src2;?>" type="audio/mpeg"   >
</audio>				
						<?php }
			if($ext1=='jpg' || $ext1=='jpeg' || $ext1=='png' || $ext1=='gif'|| $ext1=='bmp' || $ext1=='swe')
							{
			?>
								<img src="<?php echo $src2;?>" id='change' class="user-img" style="width:100%;height:500px;position:absolute; top:0;left:0px; z-index:0;" >
			
				<?php }
					?>
			<!-- end video nplay hear -->	

			<p class="set-thumb" style="text-decoration:none; width:100%;
    margin-top: -75px;
    position: absolute;"><?php if($draft_data->first_name!="" || $draft_data->middle_name!="" || $draft_data->last_name!="") { echo $draft_data->first_name.' '.$draft_data->middle_name.' '.$draft_data->last_name; } else { echo "Deceased's Profile Name"; } ?><span class="set-band" ><?php if($draft_data->date_of_birth!="") { echo 'Date: '.date('M d, Y',strtotime($draft_data->date_of_birth)).'-'.date('M d, Y',strtotime($draft_data->date_of_death)); } else { ?>Date: Oct 2,1869-Jan 30,1948<?php } ?></span></p>  
			<!--<img class="img-responsive" src="images/user.png" />-->
		</a>
			<?php	
break;				
			}
			}else{
?>
<a href="<?php echo $this->url('uploadd');?>">
			<div id="back">
            </div>
           
				<img id='change' class="user-img userimage-cls" height='500px' width='100%' src="images/user.png" style="position:absolute; top:0;left:0px; z-index:0;"/>
         <p class="set-thumb" style="text-decoration:none; width:100%;
    margin-top: -75px;
    position: absolute;"><?php if($draft_data->first_name!="" || $draft_data->middle_name!="" || $draft_data->last_name!="") { echo $draft_data->first_name.' '.$draft_data->middle_name.' '.$draft_data->last_name; } else { echo "Deceased's Profile Name"; } ?><span class="set-band" ><?php if($draft_data->date_of_birth!="") { echo 'Date: '.date('M d, Y',strtotime($draft_data->date_of_birth)).'-'.date('M d, Y',strtotime($draft_data->date_of_death)); } else { ?>Date: Oct 2,1869-Jan 30,1948<?php } ?></span></p>         
		</a>
<?php			
			}?>
   <div class="col-md-12 col-sm-12 the-controlling-images">
    <div class='test' style="">

<?php
// foe big image down menu of imagees
$count = count ( $result_thmb );
if ($count > 0) {
	foreach ( $result_thmb as $result ) {
		$ext = $result ['extension'];
		$doc_name = $result ['image_url'];
		$path = '/../module/Application/assets/images/'.$deathuserid.'/'.$doc_name;
			$info2=pathinfo($path);
	    $ext2=$info2['extension'];
		$src = $this->basepath () . $path;
		
				if($ext2=='mp4' || $ext2=='webm' || $ext2=='ogg' || $ext2=='flv'|| $ext2=='avi'|| $ext2=='wmv'|| $ext2=='mpeg'|| $ext2=='3gp'|| $ext2=='mxf'|| $ext2=='m4v'|| $ext2=='yuv'|| $ext2=='vob')
					{
					?>
<a href="#loginScreen" id="playzoom" onclick="videoPlay('<?php echo $src;?>')">	
	<img class="inputs" src="<?php echo $this->basePath('/images/videoplay.png');?>" >
</a>	
						


							<?php
	}
		if($ext2=='mp3' || $ext2=='mpeg' || $ext2=='mp2'|| $ext2=='wav'|| $ext2=='wma')
							{
			?>
				<a href="#loginScreen" id="playzoom" onclick="videoPlay('<?php echo $src;?>')">	
								<img class="inputs" src="<?php echo $this->basePath('/images/audio1.png');?>">
					</a>			
		<?php
		}
		
		if($ext2=='jpg' || $ext2=='jpeg' || $ext2=='png' || $ext2=='gif'|| $ext2=='bmp' || $ext2=='swe')
							{
	?>
<img class="inputs" src='<?php echo $src;?>' />
<?php }
	}
}?>
<?php

$path = '/addthis/images/imagenouser.png';
for($i = $count; $i < 8; $i ++) {
	?>
<img class='inputs' src='<?php echo $this->basepath(). '/addthis/images/imagenouser.png';?>' />
<?php } ?>


</div>
</div>
   <!-- <div class="back_border">Add Audio, Video and Images</div>-->
    <select class="demoa  form-controls">
      <option>Rest in Peace</option>
      <option>R.I.P.</option>
      <option>We miss you</option>
      <option>Love you Forever</option>
      <option>You won't be forgotten</option>
      <option>You will always be in our hearts</option>
      <option>Whereever you are, we love you</option>
    </select>
    
    <div class="offertings-block">  
     <div class="set-img left-img1">
      <a href="<?php echo $this->url('third');?>">
       <img class="img-responsive" src="addthis/images/mala-2.png" /> 
      </a>
    </div>
    <div class="greetings">
    				<p> Offerings </p>
    				<div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/candlee.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/diya1.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/thali.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/wreath.jpg";?>" class="inputs" title='count:1'>
                    </div>
                    <div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/namste-offering.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/ome-offering.jpg";?>" class="inputs" title='count:1'>
						  <img src="<?php echo $this->basepath(). "/addthis/images/dove.png";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/dayofdeath.png";?>" class="inputs" title='count:1'>
                    
                  </div>
                    <div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/candles.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/Growing-Tulsi-2.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/ashoka-chakra.jpg";?>"  class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/havan.jpg";?>" class="inputs" title='count:1'>
                    </div> 
                    </div>
    </div>
    
    <p class="set-thumbs"  style="cursor:pointer;">Created by: Rajeev Bhatia</p>

    <?php
   if($deathuserid){
	?>
	<span class="set-bands" onclick="privacyDivFn()" style="cursor:pointer">Privacy Settings</span>
	<?php	   
   }else {
?>
<span class="set-bands">Privacy Settings</span>

<?php   
   }
	
    ?>
  

    
  </div>

<style>
	#back {
   /* background-image: url("addthis/images/mala-3.png");*/
	background-size:100% 100%;
	height:500px;
	position:relative;
	z-index:1;
}


</style>

<!--
<p class="set-thumb">Deceased's Profile Name</p>
<span class="set-band">Date: Oct 2,1869-Jan 30,1948</span>

<div class="back_border">
	<form method="post" enctype="multipart/form-data" action="<?php echo $this->url('upload');?>" >
		<input type="file" name="file" class='btn btn-success'/>
		<input type="submit" name="sub" value="Add Audio, Video and Images" class='btn btn-success'/>
	</form>

</div>
<select class="demoa form-controls">
  <option>Rest in peace</option>
  <option>Rest in peace</option>
  <option>Rest in peace</option>
  <option>Rest in peace</option>
  <option>Rest in peace</option>
</select>
<div class="set-img"><img src="<?php echo $this->basePath('/images/adminimage.jpg');?>" /><img src="<?php echo $this->basePath('/images/adminimage.jpg');?>" /><img src="<?php echo $this->basePath('/images/adminimage.jpg');?>" /></div>

</div>-->


 
<div class="col-md-8 col-sm-12 border-left" id='newDiv' style="margin-top:5px">

	<div class="border-set">
       <div class="col-md-12">
		<div class="set-form">
      
			<h4 class="new-text">Please add an Image,Video and Audio</h4>
			<a class='right_side btn btn-default' href='javascript:history.back(1);'>Back</a>
			<hr style="border-top:1px solid #538ed5" > 
	
			<div class="row">
				<!--<div class="col-md-3">
					<a class="box" style='padding: 42px 15px;'>Cover Image</a>
				</div>-->
				
				
				<?php 
					
				 if(count($result_for)<9){
					foreach($result_for as $result){
						//$ext = $result['extension'];
				 		//echo $result['image_user'];exit;
						$doc_name = $result['image_url'];
						$path = '/../module/Application/assets/images/'.$deathuserid.'/'.$doc_name;
						$info=pathinfo($path);
	                    $ext=$info['extension'];
						
						$src = $this->basepath () . $path;
						if($ext=='mp4' || $ext=='webm' || $ext=='ogg' || $ext=='flv'|| $ext=='avi'|| $ext=='wmv'|| $ext=='mpeg'|| $ext=='3gp'|| $ext=='mxf'|| $ext=='m4v'|| $ext=='yuv'|| $ext=='vob')
						{?>
							
							  <!-- div for video play -->
		 <div id="loginScreen"> <a href="#" class="cancel" onclick="videoclose();">&times;</a>   
		   <video id="video-box" controls>
  <source src="" type="video/mp4" id="zoomvideo">
</video>
		   </div> <div id="cover" > </div> 
			
		   <!-- end video popup -->
							
							<div class='col-md-3' >
			<div class="box test" style="cursor:pointer;width:99%;" >
				<a href="#loginScreen" id="playzoom" onclick="videoPlay('<?php echo $src;?>')">	
	<img id="added-images" src="<?php echo $this->basePath('/images/videoplay.png');?>" width="158" height="104" >
</a>	
								</div>  
							</div>
						<?php } 
							if($ext=='mp3' || $ext=='mpeg' || $ext=='mp2'|| $ext=='wav'|| $ext=='wma')
							{
						?>
							<div class='col-md-3' >
								<div class="box test" style="cursor:pointer;width:99%;" >
									<a href="#loginScreen" id="playzoom" onclick="videoPlay('<?php echo $src;?>')">	
								<img id="added-images" src="<?php echo $this->basePath('/images/audio1.png');?>" width="158" height="104" >
					</a>					
								</div>
							</div>
						<?php }
			if($ext=='jpg' || $ext=='jpeg' || $ext=='png' || $ext=='gif'|| $ext=='bmp' || $ext=='swe')
							{
			?>
				
						<div class="col-md-3" >
							<div class ="box test" style="cursor:pointer;width:98%;">
								<img id="added-images" src="<?php echo $this->basepath().$path?>" width="158" height="104" >
								
							</div>
						</div>
						
				<?php }
					}
				 }?>
				<?php 
				$count = count($result_for);
				for($i=$count;$i<8;$i++)
				{ 
				if($i==0){
				?>
				<div class="col-md-3 col-sm-3 col-xs-3">
					<a class="box box-1 img-responsive cover-box-shape" > Cover image </a>
				</div>
				<?php				
				}else{
				?>
				<div class="col-md-3 col-sm-3 col-xs-3">
					<a class="box box-1 img-responsive image-box-shape">  Image <?php echo $i+1;?></a>
				</div>
				<?php 
				}
				}
				?>
				
			</div>
			
			<div class='upload_button'>
				
				<form method="post" enctype="multipart/form-data" action="<?php echo $this->url('upload');?>" >
					<input type="file" class="browse-btn" name="file"/>
					<input type="submit" name="sub" value="Add Audio, Video and Images" class='btn btn-default custom-audio-video-btn' />
				</form>
			</div>
			<div id='table_box'>
			<table class="table table-bordered">
				<tr>
					<td style="text-align:center;">Date</td>
					<td style="text-align:center;">Who</td>
					<td style="text-align:center;">File Name Selected</td>
					<td style="text-align:center;">Status</td>
					<td style="text-align:center;">Remove</td>
				</tr>
				<?php foreach($results as $result){
						$ext = $result['extension'];
						$doc_name = $result['file_name'];
						$path = '/addthis/upload/'.$doc_name;
						$src = $this->basepath().$path;
				?>
					<tr>
						<th><?php echo date("M-d-Y", strtotime($result['created'])); ?></th>
						<th><?php echo $user_name;?></th>
						<th><?php echo $result['name'];?></th>
						<th><button class="btn btn-default">Active</button></th>
						<th>
							<a href="<?php echo $this->url('delete-file').'?id='.$result['id'];?>" >
							<?php echo $this->translate('Remove');?>
					</a>
						</th>
					</tr>
				
				<?php }?>
			</table>
		</div>
		</div>
		 
		   
      </div>
    <div class="clearfix"></div>
    </div>

</div>
 
<div class="col-md-8 border-left" id="MyaccountDiv" style='display:none'>
<h3>All Death Users</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
		
        <th>S.No.</th>
        <th>FullName</th>
        <th>Gender</th>
        <th>Caste</th>
        <th>Created</th>
        <th>Edit</th>
        <th>Delete</th>
    </thead>
    
        <?php $i=1; foreach($deathUsers as $deathUser){?>
		<tbody>
           <td><?php echo $i; ?></td>
           <td><a href="<?php echo $this->url('view-account').'?id='.$deathUser['deathuser_id'];?>" ><?php echo $deathUser['first_name'].' '.$deathUser['middle_name'].' '.$deathUser['last_name']; ?> </a></td>
           <td><?php echo $deathUser['gender']; ?></td>
           <td><?php echo $deathUser['caste']; ?></td>
           <td><?php echo date('m-d-Y H:i:s',strtotime($deathUser['created'])); ?></td>
		   
           <td>
				<a href="<?php echo $this->url('editdeathuser').'?step='.$deathUser['steptoken'];?>" >Edit</a>
			</td>
			<td>
				<a href="<?php echo $this->url('delete').'?id='.$deathUser['deathuser_id'];?>" >Delete</a>
			</td>
        </tbody>
		<?php $i++; } ?>
</table>
</div>


<div class="clearfix"></div> 
     