<style>
	#view-box{
	background-color:white;
	}
	#top-view-box{
	background-color:#428bca;
	}
</style>
<script>
	function moretabs(show1,hide1){
	document.getElementById(show1).style.display="block";
	document.getElementById(hide1).style.display="none";
	}
	function backtabs(show1,hide1){
	document.getElementById(show1).style.display="block";
	document.getElementById(hide1).style.display="none";
	}
</script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/jquery.dataTables.min.css';?>"/>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
 <script src="<?php echo $this->basePath() . '/assets/js/jquery.dataTables.min.js';?>"></script>

  <?php //echo "<pre>";
  foreach($deathUsermeta as $value){
    
	  $valueall[] =$value; 
	
    if($value[meta_key]=='school')
      $school=$value[meta_value];
    else if($value[meta_key]=='college') 
      $college=$value[meta_value];
    else if($value[meta_key]=='university')        
      $university=$value[meta_value];
    else if($value[meta_key]=='others')        
      $other=$value[meta_value];  
    else if($value[meta_key]=='guest_email1')        
      $guest_email1=$value[meta_value]; 
    else if($value[meta_key]=='guest_email2')        
      $guest_email2=$value[meta_value];
    else if($value[meta_key]=='guest_pass1')        
      $guest_pass1=$value[meta_value];
    else if($value[meta_key]=='guest_pass2')        
      $guest_pass2=$value[meta_value];
    else if($value[meta_key]=='guest_offr1')        
      $guest_offr1=$value[meta_value];
    else if($value[meta_key]=='guest_offr2')        
      $guest_offr2=$value[meta_value];
    else if($value[meta_key]=='guest_msg1')        
      $guest_msg1 =$value[meta_value];
    else if($value[meta_key]=='guest_msg2')        
      $guest_msg2=$value[meta_value];  
	  else if($value[meta_key]=='employer')
	  $employer = $value[meta_value];
	  else if($value[meta_key]=='employment_history')
	  $employement = $value[meta_value];
       elseif($value[meta_key]=='professionals')
	  $professionals = $value[meta_value];
	  elseif($value[meta_key]=='personal')
	  $personal = $value[meta_value];
	  elseif($value[meta_key]=='qualities')
	  $qualities = $value[meta_value];
	  elseif($value[meta_key]=='relationship')
	  $relationship = $value[meta_value];
	  elseif($value[meta_key]=='influence')
	  $influence = $value[meta_value];
	   elseif($value[meta_key]=='refrance')
	  $refrance = $value[meta_value];
	  elseif($value[meta_key]=='social')
	  $social = $value[meta_value];
	  elseif($value[meta_key]=='link')
	  $link = $value[meta_value];
	  
	  
	
    }
	
	
	// print "<pre>";
	 // print_r($link);die;
	
     ?>
  
  <script>
  
$(document).ready( function() {
$('#radiofirst').click(function() {
$('#MyaccountDiv').hide();
$('#newDiv').show(); 
window.location="<?php echo $this->basePath('/add-death-user');?>";       
});
$('#radiosecond').click(function() {
$('#newDiv').hide();
$('#MyaccountDiv').show();
});
$('.leftgreetings img').click(function() {
	var gtype = $(this).attr('id');
	var uid = '<?php echo $deathuserid;?>';
	$.ajax({
			url : "<?php echo $this->basePath('/getguestbook');?>",
		   dataType: "json",
		   type:"post",
		   data: {
			   deathuserid: uid,
			   gtype: gtype
			},
			success: function( res ) {
				var count = Object.keys(res).length
	    		$("#guestofferimg").empty();
	    		var gview="<div id='guestofferimg' class='gustoffering-img'>";

				for(var i=0;i<count;i++) {

					gview +="<div class='gstoffimg'>";
					gview +="<span><img  class='user-img bot down side' src='"+res[i]['offer_img']+"' /></span>";
					gview +="<p>"+res[i]['created_at']+"</p>";
					gview +="<p>"+res[i]['description']+"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>";
					gview +="<p><strong>Offered By:</strong>"+res[i]['email_id']+"</p></div>";


}


 gview +="</div>";
	  $("#guestofferimg").html(gview);  		
	    		
 }
	});
});
});
function removeimg(e) {
	var isrc=$(e).siblings().attr('src');
	$(e).siblings().remove();
	$(e).remove();
	
	var offerimg=$("#offerimg").val();
	var temp=offerimg.split(",");
	for(var i=0;i<temp.length;i++){
		if (temp[i]==isrc) {
			temp.splice( temp.indexOf(temp[i]), 1 );
			break;
		}
		
	}
	$("#offerimg").val(temp.toString());
}
function tremoveimg(e) {
	var isrc=$(e).siblings().attr('src');
	$(e).siblings().remove();
	$(e).remove();
	
	var offerimg=$("#tofferimg").val();
	var temp=offerimg.split(",");
	for(var i=0;i<temp.length;i++){
		if (temp[i]==isrc) {
			temp.splice( temp.indexOf(temp[i]), 1 );
			break;
		}
		
	}
	$("#tofferimg").val(temp.toString());
}
jQuery(document).ready(function ($) {            
             
      
	  $('.test img').click(function() {
    var img = $(this).attr('src');
	$('#change').attr("src",img);
	});
            
            var options = {
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlayInterval: 4000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $SlideDuration: 500,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $DragOrientation: 3,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
                $UISearchMode: 0,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).

                $ThumbnailNavigatorOptions: {
                    $Class: $JssorThumbnailNavigator$,              //[Required] Class to create thumbnail navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always

                    $Loop: 2,                                       //[Optional] Enable loop(circular) of carousel or not, 0: stop, 1: loop, 2 rewind, default value is 1
                    $SpacingX: 3,                                   //[Optional] Horizontal space between each thumbnail in pixel, default value is 0
                    $SpacingY: 3,                                   //[Optional] Vertical space between each thumbnail in pixel, default value is 0
                    $DisplayPieces: 6,                              //[Optional] Number of pieces to display, default value is 1
                    $ParkingPosition: 204,                          //[Optional] The offset position to park thumbnail,

                    $ArrowNavigatorOptions: {
                        $Class: $JssorArrowNavigator$,              //[Requried] Class to create arrow navigator instance
                        $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                        $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                        $Steps: 6                                       //[Optional] Steps to go for each navigation request, default value is 1
                    }
                }
            };

            var jssor_slider1 = new $JssorSlider$("slider1_container", options);

            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;
                if (parentWidth)
                    jssor_slider1.$ScaleWidth(Math.min(parentWidth, 447));
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
   
document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("uploadFile").value = this.value;
};

</script>


<style>
	.right_side{
		margin-top: -40px;
		float: right;
		font-size:19px;
		font-color:'black';
		border:2px solid #777;
		
	}
	.box {
	border: 2px solid #ff6633;
    color: #777;
    display: inline-block;
    font-family: openFont2;
    font-size: 19px;
    height: 150px;
    margin-bottom: 30px;
   
    text-align: center;
	width:200px;	
	}
	
	.upload_button {
    background-color: #D2D2D2;
    border: 1px solid;
    border-radius: 4px;
    color: #777;
    cursor: pointer;
   
    font-family: openFont2;
	font-color: #ffffff;
    font-size: 17px;
    margin-bottom: 30px;
    padding: 20px 80px;
    text-decoration: none;
	width:100%;
}

	#table_box{
		border: 1px solid #ddd;
		height: 100%;
		margin-bottom: 10px;
	}
	#back {
    /*background-image: url("addthis/images/mala-3.png");*/
	background-size:100% 100%;
	height:500px;
	position:relative;
	z-index:1;
}
	.important{
		margin-left:150px;
		top:50px;
		position:absolute;
		z-index:0;
	}
	.small_img{
		background-image: url("addthis/images/mala-2.png");
		background-size:100% 100%;
		height:200px;
		position:relative;
		z-index:1;
	}
	
}

</style>


<div class="header-bottom">
	<div class="col-md-4 col-sm-4">
		<a class="logo-top" href="#">Cremation Planning <i
			class="fa fa-chevron-right"></i></a> <a class="main-slide" href="#">Announce</a>
	</div>

	<div class="col-md-4 col-sm-5 col-xs-7 bread-crum-mob ">
		<div class="button-radio">
			<input type="radio" class="css-checkbox" id="radiofirst"
				name="radiog_lite" checked="checked"> <label
				class="css-label1 radGroup1" for="radiofirst">Create New</label> <input
				type="radio" class="css-checkbox" id="radiosecond"
				name="radiog_lite" checked="checked"> <label class="css-label1 radGroup1"
				for="radiosecond" >Created Profiles</label>
		</div>
	</div>

	<div class="col-md-4 col-sm-3 col-xs-5 pull-right bread-crum-mob">
		<div class="floatr border-full pull-right">
			<a class="alls first" href="page/faq">FAQ</a><a class="alls second"
				href="page/demo">Demo</a><a class="alls third" href="page/share">Share</a>
		</div>
	</div>
	<div class="flash_message"> <?php echo $message; ?></div>
	<div class="clearfix"></div>
</div>

<div class="section-band">
<div class="col-md-4 border-right text-center" style="height:300px;">
    <?php 

				if(sizeof($imagesres)>0){			
			foreach($imagesres as $result2){
				
				$doc_name2 = $result2['image_url'];
				
				$path2 = '/../module/Application/assets/images/'.$deathuserid.'/'.$doc_name2;
			
				$src2 = $this->basepath().$path2;
			?>
			<a href="#">
			<div id="back"></div>
			<img id='change' class="user-img" height='500px' width='100%' src='<?php echo $src2;?>' style="position:absolute; top:0;left:0px; z-index:0;" />
		
			<p class="set-thumb" style="text-decoration:none; width:100%;
    margin-top: -75px;
    position: absolute;"><?php if($deathUser['first_name']!="" || $deathUser['middle_name']!="" || $deathUser['last_name']!="") { echo $deathUser['first_name'].' '.$deathUser['middle_name'].' '.$deathUser['last_name']; } else { echo "Deceased's Profile Name"; } ?><span class="set-band" ><?php if($deathUser['date_of_birth']!="") { echo 'Date: '.date('M d, Y',strtotime($deathUser['date_of_birth'])).'-'.date('M d, Y',strtotime($deathUser['date_of_death'])); } else { ?>Date: Oct 2,1869-Jan 30,1948<?php } ?></span></p>   
			<!--<img class="img-responsive" src="images/user.png" />-->
		</a>
			<?php	
break;				
			}
			}else{
?>
<a href="#">
			<div id="back">
            </div>
           
				<img id='change' class="user-img" height='500px' width='100%' src="images/user.png" style="position:absolute; top:0;left:0px; z-index:0;"/>
         <p class="set-thumb" style="text-decoration:none; width:100%;
    margin-top: -75px;
    position: absolute;"><?php if($deathUser['first_name']!="" || $deathUser['middle_name']!="" || $deathUser['last_name']!="") { echo $deathUser['first_name'].' '.$deathUser['middle_name'].' '.$deathUser['last_name']; } else { echo "Deceased's Profile Name"; } ?><span class="set-band" ><?php if($deathUser['date_of_birth']!="") { echo 'Date: '.date('M d, Y',strtotime($deathUser['date_of_birth'])).'-'.date('M d, Y',strtotime($deathUser['date_of_death'])); } else { ?>Date: Oct 2,1869-Jan 30,1948<?php } ?></span></p>        
		</a>
<?php			
			}?>

  <div class="col-md-12 col-sm-12 the-controlling-images">
  <div class='test' style="display: block; margin:10px 0;">

<?php

$count = count ( $imagesthumb );
//echo $count;exit;
if ($count > 0) {
	foreach ( $imagesthumb as $result ) {
		$ext = $result ['extension'];
		$doc_name = $result ['image_url'];
		$path = '/../module/Application/assets/images/'.$deathuserid.'/'.$doc_name;
		$src = $this->basepath () . $path;
		?>
<img class="inputs" src='<?php echo $src;?>' />
<?php }}?>
<?php

$path = '/addthis/images/imagenouser.png';
for($i = $count; $i < 8; $i ++) {
	?>
<img class='inputs' src='<?php echo $this->basepath(). '/addthis/images/imagenouser.png';?>' />
<?php } ?>


</div>
  </div>
   <!-- <div class="back_border">Add Audio, Video and Images</div>-->
    <select class="demoa  form-controls">
      <option>Rest in Peace</option>
      <option>R.I.P.</option>
      <option>We miss you</option>
      <option>Love you Forever</option>
      <option>You won't be forgotten</option>
      <option>You will always be in our hearts</option>
      <option>Whereever you are, we love you</option>
    </select>
   
   <div class="offertings-block">
   <div class="set-img left-img1">
      <a href="<?php echo $this->url('third');?>">
       <img src="addthis/images/mala-2.png" /> 
      </a>
    </div>
    <div class="greetings">
   <?php 
	//print_r($getwreathcount);   
   ?>
    				<p> <span>Offerings</span> </p>
    				<div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/candlee.jpg";?>" class="inputs" title="<?php if(count($getcandlecount)>0){foreach($getcandlecount as $getcandle){ echo 'Count: '.$getcandle['cofferings']; }}else{ echo 'Count: 0';}?>">
                    <img src="<?php echo $this->basepath(). "/addthis/images/diya1.jpg";?>" class="inputs" title="<?php if(count($getdiyacount)>0){ foreach($getdiyacount as $getdiya){ echo 'Count: '.$getdiya['cofferings']; }}else{ echo 'Count: 0';}?>">
                    <img src="<?php echo $this->basepath(). "/addthis/images/thali.jpg";?>" class="inputs" title="<?php if(count($getthalicount)>0){foreach($getthalicount as $getthali){ echo 'Count: '.$getthali['cofferings']; }}else{ echo 'Count: 0';}?>">
                    <img src="<?php echo $this->basepath(). "/addthis/images/wreath.jpg";?>" class="inputs"title="<?php if(count($getwreathcount)>0){foreach($getwreathcount as $getwreath){ echo 'Count: '.$getwreath['cofferings']; }}else{ echo 'Count: 0';}?>">
                    </div>
                    <div class="offering-row1">
                   <img src="<?php echo $this->basepath(). "/addthis/images/namste-offering.jpg";?>" class="inputs" title="<?php if(count($getnamaskarcount)>0){foreach($getnamaskarcount as $getnamaskar){ echo 'Count: '.$getnamaskar['cofferings']; }}else{ echo 'Count: 0';}?>">
                    <img src="<?php echo $this->basepath(). "/addthis/images/ome-offering.jpg";?>" class="inputs" title="<?php if(count($getomcount)>0){foreach($getomcount as $getom){ echo 'Count: '.$getom['cofferings']; }}else{ echo 'Count: 0';}?>">
                    <img src="<?php echo $this->basepath(). "/addthis/images/candles.jpg";?>" class="inputs" title="<?php if(count($getcandlescount)>0){foreach($getcandlescount as $getcandles){ echo 'Count: '.$getcandles['cofferings']; }}else{ echo 'Count: 0';}?>">
                    <img src="<?php echo $this->basepath(). "/addthis/images/Growing-Tulsi-2.jpg";?>" class="inputs" title="<?php if(count($gettreecount)>0){foreach($gettreecount as $gettree){ echo 'Count: '.$gettree['cofferings']; }}else{ echo 'Count: 0';}?>">
                    </div>
                    <div class="offering-row1">
                   <img src="<?php echo $this->basepath(). "/addthis/images/dove.png";?>" class="inputs" title="<?php if(count($getdovecount)>0){foreach($getdovecount as $getdove){ echo 'Count: '.$getdove['cofferings']; }}else{ echo 'Count: 0';}?>">
                    <img src="<?php echo $this->basepath(). "/addthis/images/dayofdeath.png";?>" class="inputs" title="<?php if(count($getdeadcount)>0){foreach($getdeadcount as $getdead){ echo 'Count: '.$getdead['cofferings']; }}else{ echo 'Count: 0';}?>">
                    <img src="<?php echo $this->basepath(). "/addthis/images/ashoka-chakra.jpg";?>"  class="inputs" title="<?php if(count($getashokachakracount)>0){foreach($getashokachakracount as $getashokachakra){ echo 'Count: '.$getashokachakra['cofferings']; }}else{ echo 'Count: 0';}?>">
                    <img src="<?php echo $this->basepath(). "/addthis/images/havan.jpg";?>" class="inputs" title="<?php if(count($gethavankundcount)>0){foreach($gethavankundcount as $gethavankund){ echo 'Count: '.$gethavankund['cofferings']; }}else{ echo 'Count: 0';}?>">
                             </div>
                    </div>
   </div>
    <p class="set-thumbs"  style="cursor:pointer;">Created by: Rajeev Bhatia</p>
    <?php
   if($deathuserid){
	?>
	<span class="set-bands" onclick="privacyDivFn()" style="cursor:pointer">Privacy Settings</span>
	<?php	   
   }else {
?>
<span class="set-bands">Privacy Settings</span>
<?php   
   }
	
    ?>
  </div>
<div class="col-md-8 border-left userinfo-tabs" id='newDiv' >
<ul role="tablist" class="nav nav-tabs navs newLayout"  id="first" style="display:block;">
	
<li class="active nav-nav12-nav" role="presentation"><a aria-expanded="false" aria-controls="info" data-toggle="tab" role="tab" id="info-tab" href="#info" style="height:35px;;">Info</a></li>
      <li class="nav-nav12-nav" role="presentation" class=""><a aria-controls="edu" data-toggle="tab" id="edu-tab" role="tab" href="#edu" aria-expanded="false" style="height:35px;">Edu</a></li>
	   <li class="nav-nav12-nav" role="presentation" class=""><a aria-controls="family" data-toggle="tab" id="family-tab" role="tab" href="#family" aria-expanded="false" style="height:35px;">Family</a></li>
	    <li class="nav-nav12-nav" role="presentation" class=""><a aria-controls="guestbook" data-toggle="tab" id="guestbook-tab" role="tab" href="#guestbook" aria-expanded="false" style="height:35px;">Guestbook</a></li>
		 <li class="nav-nav12-nav" role="presentation" class=""><a aria-controls="tributes" data-toggle="tab" id="tributes-tab" role="tab" href="#tributes" aria-expanded="false" style="height:35px;">Tributes</a></li>
		  <li class="nav-nav12-nav" role="presentation" class=""><a aria-controls="donate" data-toggle="tab" id="donate-tab" role="tab" href="#donate" aria-expanded="false" style="height:35px;">Donate</a></li>
		
	  <li role="presentation" class="nav-nav12-nav"><a  style="height:35px;cursor:pointer" onclick="moretabs('second','first')">More...</a></li> 
</ul>
<ul role="tablist" class="nav nav-tabs navs newLayout"  id="second" style="display:none;">
			 <li class="nav-nav12-nav" role="presentation" style="width:23%;" class=""><a aria-controls="achievement" data-toggle="tab" id="achievement-tab" role="tab" href="#achievement" aria-expanded="false" style="height:35px;">Employment History</a></li>
		  <li class="nav-nav12-nav" role="presentation" class="" style="width:22%;"><a aria-controls="home" data-toggle="tab" id="home-tab" role="tab" href="#home" aria-expanded="false" style="height:35px;">Achivements  </a></li>
		  <li class="nav-nav12-nav" role="presentation" class="" style="width:20%;"><a aria-controls="profile" data-toggle="tab" id="profile-tab" role="tab" href="#profile" aria-expanded="false" style="height:35px;">Personal Honors</a></li>
      	  <li class="nav-nav12-nav" role="presentation" class="" style="width:20%;"><a aria-controls="footprints" data-toggle="tab" id="footprints-tab" role="tab" href="#footprints" aria-expanded="false" style="height:35px;" >Digital Footprints</a></li>
		  <li role="presentation" class="nav-nav12-nav" style="width:12%;"><a aria-controls="more" data-toggle="tab" id="more-tab" role="tab"  aria-expanded="false" style="height:35px;cursor:pointer" onclick="backtabs('first','second')">Back...</a></li> 
   </p>
		 
    </ul>
    <div class="tab-content" id="myTabContent" >
      <div aria-labelledby="info-tab" id="info" class="tab-pane fade active in" role="tabpanel" >
       
	   <div class="new_submit" id="top-view-box">User Information</div>

<div class="set-text" id="view-box">
<div class="top-margin floatl" >

<p class="floatl set_width1"  ><b class="user-info">Name : </b>
 <span class=""><?php echo strtoupper($deathUser['salutation']).' '.$deathUser['first_name'].' '.$deathUser['middle_name'].' '.$deathUser['last_name']; ?> </span> </p> 
<!--<p class="floatl set_width1"><b>Name<span>:</span></b></p>
<p class="floatl"><?php echo strtoupper($deathUser['salutation']).' '.$deathUser['first_name'].' '.$deathUser['middle_name'].' '.$deathUser['last_name']; ?></p>-->
</div>

<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Aka<span>:</span></b>
<span class=""><?php echo $deathUser['aka'];?> </span> </p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Gender<span>:</span></b>
<span class=""><?php echo $deathUser['gender'];?> </span> </p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Address<span>:</span></b>
<span class=""><?php echo $deathUser['resident'];?> </span> </p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b  class="user-info">Occupation<span>:</span></b>
<span class=""><?php echo $deathUser['occupation'];?> </span> </p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Caste<span>:</span></b>
<span class=""><?php echo $deathUser['caste'];?> </span> </p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Gotra<span>:</span></b>
<span class=""><?php echo $deathUser['gotra'];?> </span> </p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Place of Death<span>:</span></b>
<span class=""><?php echo $deathUser['death_place'];?></p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Cause of Death<span>:</span></b>
<span class=""><?php echo $deathUser['death_cause'];?> </span> </p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Time of Death<span>:</span></b>
<span class=""><?php echo $deathUser['death_time'];?> </span> </p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Date of Birth<span>:</span></b>
<span class=""><?php echo $deathUser['date_of_birth'];?> </span> </p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Date of Death<span>:</span></b>
<span class=""><?php echo $deathUser['date_of_death'];?> </span></p>
</div>
<div class="clearfix"></div>

<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Age (Approximate)<span>:</span></b>
<span class=""><?php echo (int)$deathUser['age'];?> Years </span> </p>
</div>
<div class="clearfix"></div>

</div>

	   
      </div>
      <div aria-labelledby="edu-tab" id="edu" class="tab-pane fade" role="tabpanel" >
	  
	  
	  <div class="new_submit" id="top-view-box">Education Details</div>

<div class="set-text" id="view-box">
<div class="top-margin floatl">
<p class="floatl set_width1"><b class="user-info">School Name<span>:</span></b>
<span class=""><?php echo $school; ?></span></p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b class="user-info">College Name<span>:</span></b>
<span class=""><?php echo $college; ?></span></p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b class="user-info">University Name<span>:</span></b>
<span class=""><?php echo $university; ?></span></p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Other Qualification Name<span>:</span></b>
<span class=""> <?php echo $other; ?></span></p>
</div>
<div class="clearfix"></div>
</div>
	  
	  
       
      </div>
	  
	  
	  
	      <div aria-labelledby="family-tab" id="family" class="tab-pane fade form-details-informations" role="tabpanel">
          <div class="the-contact-informationss">
          <div class="the-controlling-mail">
      
<div class="form-more-information-details">
	  
	  <div class="new_submit-survy" id="top-view-box">Survived By</div>
        <?Php foreach($getfamily as $family){  ?>
        <div class="set-text1" id="view-box">
        <div class="top-margin floatl">
        <p class="floatl set_width1"><b class="user-info">Relationship</b>
        <span class=""><?php echo $family['type'] ?></span></p>
        </div>
        <div class="clearfix"></div>
        <div class="set-all">
        <p class="floatl set_width1"><b class="user-info">Name</b>
        <span class=""> <?php echo $family['first_name'].' '.$family['middle_name'].' '.$family['last_name']; ?></span></p>
        </div>
        <div class="clearfix"></div>
        </div>
	  <?php } ?>
	  
      </div>
      </div>
      
      <div class="the-controlling-mail1">
	  <div class="form-more-information-details1">
      
      <div class="new_submit" id="top-view-box">Predeceased By</div>
        <?Php foreach($getfamilyPre as $familyPre){  ?>
        <div class="set-text" id="view-box">
        <div class="top-margin floatl">
        <p class="floatl set_width1"><b class="user-info">Relationship</b>
        <span class=""><?php echo $familyPre['type'] ?></span></p>
        </div>
        <div class="clearfix"></div>
        <div class="set-all">
        <p class="floatl set_width1"><b class="user-info">Name</b>
        <span class=""><?php echo $familyPre['first_name'].' '.$familyPre['middle_name'].' '.$familyPre['last_name']; ?></span></p>
        </div>
        <div class="clearfix"></div>
        </div>
    <?php } ?>
      </div>
      </div>
      </div>
      </div>
	  
	  
	  
	  <div aria-labelledby="guestbook-tab" id="guestbook" class="tab-pane fade" role="tabpanel">
	  
	 
	  <div class="new_submit" id="top-view-box">Guestbook Details</div>
<?php $link= $this->url('sendguestoffer',array(), array('force_canonical' => true)).'?id='.$deathuserid;?>
<form class="form-inline" method="post" action="<?php echo $link; ?>">
<div class="border-set">
<div class="col-md-12">
<div class="set-form">
				
           
<div id="guestofferimg" class="gustoffering-img">
<table id="guesttable">
<thead>
<tr>
<th></th>
</tr>
</thead>
<tbody>
<?php foreach($guestbook as $gb){
$temp=explode(",",$gb['offer_img']);
?>
<tr>
<td>
<div class="gstoffimg">
<div class="set-img left-imgimg1">
      <a href="/ANTHIM/Source/public/third">
       <img width="50px" height="50px" src="addthis/images/mala-2.png"> 
      </a>
    </div>
<!--
    <div class="greetings" style="display: block; margin:0 6px 10px 6px; width:24% !important; float:left;">
   
    			
    				<div class="offering-row1">
                    <img src="<?php //echo $this->basepath(). "/addthis/images/candlee.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php //echo $this->basepath(). "/addthis/images/diya1.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php //echo $this->basepath(). "/addthis/images/thali.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php //echo $this->basepath(). "/addthis/images/wreath.jpg";?>" class="inputs" title='count:1'>
                    </div>
                    <div class="offering-row1">
                    <img src="<?php //echo $this->basepath(). "/addthis/images/namste-offering.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php //echo $this->basepath(). "/addthis/images/ome-offering.jpg";?>" class="inputs" title='count:1'>
						  <img src="<?php //echo $this->basepath(). "/addthis/images/dove.png";?>" class="inputs" title='count:1'>
                    <img src="<?php //echo $this->basepath(). "/addthis/images/dayofdeath.png";?>" class="inputs" title='count:1'>
                    
                  </div>
                    <div class="offering-row1">
                    <img src="<?php //echo $this->basepath(). "/addthis/images/candles.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php //echo $this->basepath(). "/addthis/images/Growing-Tulsi-2.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php //echo $this->basepath(). "/addthis/images/ashoka-chakra.jpg";?>"  class="inputs" title='count:1'>
                    <img src="<?php //echo $this->basepath(). "/addthis/images/havan.jpg";?>" class="inputs" title='count:1'>
                    </div> 
                    </div>
-->
                    <div class="" style="display: block; margin:0 6px 10px 6px; width:77% !important; float:left;padding-left:15px;" >
                    <p><strong>Offered Date: </strong><?php echo $gb['created_at'];?></p>  
                    <p><strong>Offered By: </strong> <?php echo $gb['email_id'];?></p> 
                    <p><strong>Description: </strong><?php echo $gb['description'].$gb['description'].$gb['description'];?></p>   

</div>
   </div>
             
</div>
<!--<div class="gstoffimg">
<?php for($i=0;$i<=count($temp)-1;$i++) { ?>
<span><img  class='user-img bot down side' src="<?php echo $temp[$i];?>" style="width:35px; border: 3px solid #ff7f50; border-bottom: 3px solid #ff7f50; margin-right: 1px;" /></span>
<?php } ?>
<p><?php echo $gb['created_at'];?></p>
<p><?php echo $gb['description'];?></p>
<p><strong>Offered By:</strong> <?php echo $gb['email_id'];?></p>
</div>-->
</td>
	</tr>
<?php	
}
?>
</tbody>
</table>
</div>
     <div class="clearfix"></div>
               
                <input type="hidden" name="user[offerimg]" id="offerimg" value=""/>
 <input type="hidden" name="user[offertype]" id="offertype" value=""/>
		<!--	<p class="set-offering" style="float:left">Offerings</p> <span id="appendimg" style="margin-left:26px;"></span>-->
	
 <div class="clearfix"></div>
		
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<div>
		<!--<button class="saveButton" type="submit">Save to my Draft</button>-->
		<!--<button class="saveButton" style="float:right" type="submit">Send</button>-->
       <!--  <span style="float: right;"><a class="sendButton">Send</a></span>-->
	</div>
</form>
<script>
$(document).ready( function() {
$('.inputs').hover( function() {
        $(this).attr('title').fadeIn(300);
    }, function() {
        $(this).attr('title').fadeOut(100);
    });

});
$("#guesttable").dataTable({
		"bFilter": false,
		"ordering": false	
	}); 
 $('.greetings img').click(function() {
 var imagecount = $('#appendimg img').length;
if(imagecount==10){	
alert("Offering can be done only 10");
}
else {
var img = $(this).attr('src');
var id = $(this).attr('id');
alert(id);
//$('#greet').attr("src",img);
$('#appendimg').append("<div style='float:left'><img  class='user-img bot' src="+img+" /><i class='fa fa-times cross' onclick='removeimg(this)'></i></div>");
var offerimg=$("#offerimg").val();
if (offerimg!="") {
	$("#offerimg").val(offerimg+","+img);
}else {
	$("#offerimg").val(img);
}
var offertype=$("#offertype").val();
if (offertype!="") {
	$("#offertype").val(offertype+","+id);
}else {
	$("#offertype").val(id);
}

}
});

</script>

<div class="clearfix"></div>

       
      </div>
	  
	  
	   <div aria-labelledby="tributes-tab" id="tributes" class="tab-pane fade" role="tabpanel">
	  
	   <div class="new_submit" id="top-view-box">Tributes Details</div>
       <?php $link= $this->url('sendtributeoffer',array(), array('force_canonical' => true)).'?id='.$deathuserid;?>
<form class="form-inline" method="post" action="<?php echo $link; ?>">
	<div class="border-set">
		<div class="col-md-12">
			<div class="set-form">
<div id="tributeofferimg" class="gustoffering-img">
<table id="tribtable">
<thead>
<tr>
<th></th>
</tr>
</thead>
<tbody>
<?php

 foreach($tribute as $trgb){
 ?>
 <tr>
 <td>
 <?php	
	$trtemp=explode(",",$trgb['offer_img']);
	
?>
<div class="gstoffimg">
<div class="set-img left-imgimg1">
      <a href="/ANTHIM/Source/public/third">
       <img width="50px" height="50px" src="addthis/images/mala-2.png"> 
      </a>
    </div>
    <div class="greetings" style="display: block; margin:0 6px 10px 6px; width:24% !important; float:left;">
   
    			
    				<div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/candlee.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/diya1.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/thali.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/wreath.jpg";?>" class="inputs" title='count:1'>
                    </div>
                    <div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/namste-offering.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/ome-offering.jpg";?>" class="inputs" title='count:1'>
						  <img src="<?php echo $this->basepath(). "/addthis/images/dove.png";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/dayofdeath.png";?>" class="inputs" title='count:1'>
                    
                  </div>
                    <div class="offering-row1">
                    <img src="<?php echo $this->basepath(). "/addthis/images/candles.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/Growing-Tulsi-2.jpg";?>" class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/ashoka-chakra.jpg";?>"  class="inputs" title='count:1'>
                    <img src="<?php echo $this->basepath(). "/addthis/images/havan.jpg";?>" class="inputs" title='count:1'>
                    </div> 
                    </div>
                    <div class="offering-data-block" style="">
                    <p><strong>Offered Date: </strong><?php echo $trgb['created_at'];?></p>  
                    <p><strong>Offered By: </strong> <?php echo $trgb['email_id'];?></p> 
                    <p><strong>Description: </strong><?php echo $trgb['description'];?></p>   

</div>
   </div>
<!--<div class="gstoffimg">
<?php for($i=0;$i<count($trtemp);$i++) { ?>
<span><img  class='user-img bot down side' src="<?php echo $trtemp[$i];?>" style="width:35px; border: 3px solid #ff7f50; border-bottom: 3px solid #ff7f50; margin-right: 1px;" /></span>
<?php } ?>
<p><?php echo $trgb['created_at'];?></p>
<p><?php echo $trgb['description'];?></p>
<p><strong>Offered By:</strong> <?php echo $trgb['email_id'];?></p>
</div>-->
</td>
</tr>
<?php
}
?>
</tbody>
</table>
</div>	
<div class="clearfix"></div>

				
                <div class="clearfix"></div>
                

	</div>
		</div>
		
	</div>
	<div>
		<!--<button class="saveButton" type="submit">Save to my Draft</button>-->
		<!--<button class="saveButton" style="float:right" type="submit">Send</button>-->
       <!--  <span style="float: right;"><a class="sendButton">Send</a></span>-->
	</div>
</form>
<script>
$(document).ready( function() {
$('.inputs').hover( function() {
        $(this).attr('title').fadeIn(300);
    }, function() {
        $(this).attr('title').fadeOut(100);
    });
  
});
$("#tribtable").dataTable({
		"bFilter": false,
		"ordering": false	
	}); 
 $('.tgreetings img').click(function() {
 var imagecount = $('#tappendimg img').length;
if(imagecount==10){	
alert("Offering can be done only 10");
}
else {
var img = $(this).attr('src');
//$('#greet').attr("src",img);
$('#tappendimg').append("<div style='float:left'><img  class='user-img bot' src="+img+" /><i class='fa fa-times cross' onclick='tremoveimg(this)'></i></div>");
var offerimg=$("#tofferimg").val();
if (offerimg!="") {
	$("#tofferimg").val(offerimg+","+img);
}else {
	$("#tofferimg").val(img);
}


}
});

</script>
      </div>
	  
	  
	   <div aria-labelledby="donate-tab" id="donate" class="tab-pane fade" role="tabpanel">

	   <div class="border-set">
       <div class="col-md-12">
       <div class="set-form">
      
	  <h4 class="new-text">In memory of the person, please make an impact through donations to</h4>
	  <h3 class="new-fonts">Antimsanskar Default Suggestion</h3>
	
	<div class="row">
	<div class="col-md-4">
	<a class="view" href="#">Cleaning holy rivers</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Cause of death related - like Cancer Heart Disease</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Religious Beliefs</a>
	</div>
	</div>
	
	<div class="row">
	<div class="col-md-4">
	<a class="view" href="#">Soup Chicken, Food &amp; Shelter</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Scholarships and Education</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Research and Development</a>
	</div>
	</div>
	<!--
	<div class="row">
	<div class="col-md-4">
	<a class="view" href="#">Soup Chicken, Food &amp; Shelter</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Scholarships and Education</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Research and Development</a>
	</div>
	</div> -->
	
	<a href="#" class="fastButton">Mydonations: Click here to choose from a complete list of impact categories</a>
	  
      </div>
       </div>
       <div class="clearfix"></div>
       </div>
	   
	  
	   
	   <div><a class="toolButton" href="#">Tools</a><a class="saveButton">Save to my account</a><a class="sendButton">Send</a></div>
       
      </div>
     <div class="clearfix"></div>
	 
<div aria-labelledby="achievement-tab" id="achievement" class="tab-pane fade" role="tabpanel">
<div class="new_submit" id="top-view-box">Employment History</div>
<div class="set-text" id="view-box">
<div class="top-margin floatl">
<p class="floatl set_width1"><b class="user-info">Employer Name<span>:</span></b>
<span class=""><?php echo $employer;?> </span> </p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Employment History<span>:</span></b>
<span class=""><?php echo $employement;?></span> </p>
</div>
<div class="clearfix"></div>
</div>
</div>
<div aria-labelledby="home-tab" id="home" class="tab-pane fade " role="tabpanel">
<div class="new_submit" id="top-view-box">Achivements & Awards</div>
<div class="set-text" id="view-box">
<div class="top-margin floatl">
<p class="floatl set_width1"><b class="user-info">Professionals<span>:</span></b>
<span class=""> <?php echo $professionals;?></span> </p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Personal<span>:</span></b>
<span class=""><?php echo $personal;?></span> </p>
</div>
<div class="clearfix"></div>
</div>
</div>

<div aria-labelledby="profile-tab" id="profile" class="tab-pane fade" role="tabpanel">
<div class="new_submit" id="top-view-box">Personal Honors</div>
<div class="set-text" id="view-box">
<div class="top-margin floatl">
<p class="floatl set_width1"><b >Qualities <span>:</span></b> <?php echo $qualities;?> </p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b >Relationship <span>:</span></b>
<span class=""><?php echo $relationship?></span> </p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b >Influence <span>:</span></b>
<span class=""><?php echo $influence;?></span> </p>
</div>
<div class="clearfix"></div>
</div>
</div>

	  <div aria-labelledby="footprints-tab" id="footprints" class="tab-pane fade" role="tabpanel">
<div class="new_submit" id="top-view-box">Digital Footprints & Links</div>
<div class="set-text" id="view-box">
<div class="top-margin floatl">
<p class="floatl set_width1"><b class="user-info">Links<span>:</span></b>
<span class=""><?php echo $link;?></span> </p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b class="user-info">References<span>:</span></b>
<span class=""><?php echo $refrance;?></span> </p>
</div>
<div class="clearfix"></div>
<div class="set-all">
<p class="floatl set_width1"><b class="user-info">Social Sites<span>:</span></b>
<span class=""><?php echo $social;?></span> </p>
</div>
<div class="clearfix"></div>
</div>
</div>

	<div aria-labelledby="more-tab" id="more" class="tab-pane fade" role="tabpanel">

<div class="border-set">
       <div class="col-md-12">
       <div class="set-form">
      
	  <form>
	  <div class="row">
	  <div class="col-md-6">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="my-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  </div>
  <div class="col-md-6">
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="my-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  </div>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Message</label>
    <textarea placeholder="Message here..." rows="5" class="my-controls"></textarea>
  </div>
   <div class="form-group">
    <label for="exampleInputPassword1">Select offerings:</label>
    <select class="my-control1 demoak">
  <option>First</option>
  <option>Second</option>
  <option>Third</option>
  <option>Fourth</option>
  <option>Fifth</option>
  <option>Sixth</option>
  <option>Seventh</option>
  <option>Eighth</option>
</select>
  </div>
  </form>

	  
      </div>
       </div>
       <div class="clearfix"></div>
       </div>
	   
	   
	   <div class="border-sets">
       <div class="col-md-12">
       <div class="set-form">
      
	  <form>
	  <div class="row">
	  <div class="col-md-6">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="my-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  </div>
  <div class="col-md-6">
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="my-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  </div>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Message</label>
    <textarea placeholder="Message here..." rows="5" class="my-controls"></textarea>
  </div>
   <div class="form-group">
    <label for="exampleInputPassword1">Select offerings:</label>
    <select class="my-control1 demoak">
  <option>First</option>
  <option>Second</option>
  <option>Third</option>
  <option>Fourth</option>
  <option>Fifth</option>
  <option>Sixth</option>
  <option>Seventh</option>
  <option>Eighth</option>
</select>
  </div>
  </form>

	  
      </div>
       </div>
       <div class="clearfix"></div>
       </div>
	  
	   
	   <div><a class="toolButton" href="#">Tools</a><a class="saveButton">Save to my account</a><a class="sendButton">Send</a></div>
       
      </div>
	  
	  
	  <div aria-labelledby="profile-tab" id="profile" class="tab-pane fade" role="tabpanel">

<div class="border-set">
       <div class="col-md-12">
       <div class="set-form">
      
	  <h4 class="new-text">In memory of the person, please make an impact through donations to</h4>
	  <h3 class="new-fonts">Antimsanskar Default Suggestion</h3>
	
	<div class="row">
	<div class="col-md-4">
	<a class="view" href="#">Cleaning holy rivers</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Cause of death related - like Cancer Heart Disease</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Religious Beliefs</a>
	</div>
	</div>
	
	<div class="row">
	<div class="col-md-4">
	<a class="view" href="#">Soup Chicken, Food &amp; Shelter</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Scholarships and Education</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Research and Development</a>
	</div>
	</div>
	
	<div class="row">
	<div class="col-md-4">
	<a class="view" href="#">Soup Chicken, Food &amp; Shelter</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Scholarships and Education</a>
	</div>
	<div class="col-md-4">
	<a class="view" href="#">Research and Development</a>
	</div>
	</div> 
	
	<a href="#" class="fastButton">Mydonations: Click here to choose from a complete list of impact categories</a>
	  
      </div>
       </div>
       <div class="clearfix"></div>
       </div>
	   
	  
	   
	   <div><a class="toolButton" href="#">Tools</a><a class="saveButton">Save to my account</a><a class="sendButton">Send</a></div>
       
      </div>
      
    </div>
</div>

<div class="col-md-8 border-left" id="MyaccountDiv" style='display:none'>
<h3>All Death Users</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
		
        <th>S.No.</th>
        <th>FullName</th>
        <th>Gender</th>
        <th>Caste</th>
        <th>Created</th>
        <th>Edit</th>
        <th>Delete</th>
    </thead>
    
        <?php $i=1; foreach($deathUsers as $deathUser){?>
		<tbody>
           <td><?php echo $i; ?></td>
           <td><a href="<?php echo $this->url('view-account').'?id='.$deathUser['deathuser_id'];?>" ><?php echo $deathUser['first_name'].' '.$deathUser['middle_name'].' '.$deathUser['last_name']; ?> </a></td>
           <td><?php echo $deathUser['gender']; ?></td>
           <td><?php echo $deathUser['caste']; ?></td>
           <td><?php echo date('m-d-Y H:i:s',strtotime($deathUser['created'])); ?></td>
		   
           <td>
				<a href="<?php echo $this->url('editdeathuser').'?step='.$deathUser['steptoken'];?>" >Edit</a>
			</td>
			<td>
				<a href="<?php echo $this->url('delete').'?id='.$deathUser['deathuser_id'];?>" onclick="return confirm('Are you sure to delete this row')" >Delete</a>
			</td>
        </tbody>
		<?php $i++; } ?>
</table>
</div>


<div class="clearfix"></div>
</div>


</div>
 
</div>
<script type="text/javascript">
document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("uploadFile").value = this.value;
};

	
</script>
</body>
</html>